/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import datos.AlumnoDAO;
import datos.BimestreDAO;
import datos.CursoDAO;
import datos.DocenteDAO;
import datos.MatriculaDAO;
import entidad.*;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Piero
 */
public class DialogListasFromDocente extends javax.swing.JDialog {

    ArrayList<Curso> listaCursos = new ArrayList<>();
    ArrayList<Alumno> la = new ArrayList<>();
    Docente d = null;    
    Curso c = new Curso();
    Curso cursoSelec = null;
    DefaultTableModel modelo = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    public DialogListasFromDocente() {
        super(FrmInicioDocente.getInstancia(),true);
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void setD(Docente docente){
        d = docente;
        llenarDatos();
        try {
            listaCursos = CursoDAO.getInstancia().mostrarCursosPorDocente(d.getDni());
            llenarCursos();
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR: "+e.getMessage(),"",0);
        }
        
    }
    private void llenarCursos(){
        for(int i=0; i<listaCursos.size();i++){
            cboCurso.addItem(listaCursos.get(i).getNombre());
        }
    }
    
    private void llenarDatos(){
       lblDocente.setText(d.getNombre()+" "+d.getApellido_p()+" "+d.getApellido_m());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cboCurso = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        lblDocente = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblGrado1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lblGrado = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblSeccion = new javax.swing.JLabel();
        pnlRed = new javax.swing.JPanel();
        btnImprimirMatricula = new javax.swing.JButton();
        btnSalir4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 54)); // NOI18N
        jLabel2.setText("LISTAR ALUMNOS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 560, 50));

        cboCurso.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        cboCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECCIONAR>" }));
        cboCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCursoActionPerformed(evt);
            }
        });
        getContentPane().add(cboCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 380, 40));

        jLabel12.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(25, 0, 58));
        jLabel12.setText("DOCENTE");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        lblDocente.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        getContentPane().add(lblDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 380, 30));

        jLabel14.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(25, 0, 58));
        jLabel14.setText("GRADO");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-todos.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 70, 70));

        lblGrado1.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        getContentPane().add(lblGrado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 80, 30));

        jPanel2.setBackground(new java.awt.Color(26, 2, 58));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 800));

        jLabel15.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(25, 0, 58));
        jLabel15.setText("CURSO");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        lblGrado.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        getContentPane().add(lblGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 120, 30));

        jLabel16.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(25, 0, 58));
        jLabel16.setText("SECCION");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, -1, -1));

        lblSeccion.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        getContentPane().add(lblSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 120, 30));

        pnlRed.setBackground(new java.awt.Color(194, 36, 45));
        pnlRed.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnImprimirMatricula.setBackground(new java.awt.Color(255, 255, 255));
        btnImprimirMatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-reporte.png"))); // NOI18N
        btnImprimirMatricula.setText("REPORTE");
        btnImprimirMatricula.setBorder(null);
        btnImprimirMatricula.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnImprimirMatricula.setMinimumSize(new java.awt.Dimension(200, 200));
        btnImprimirMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirMatriculaActionPerformed(evt);
            }
        });
        pnlRed.add(btnImprimirMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 180, 40));

        btnSalir4.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-salir.png"))); // NOI18N
        btnSalir4.setText("SALIR");
        btnSalir4.setBorder(null);
        btnSalir4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir4ActionPerformed(evt);
            }
        });
        pnlRed.add(btnSalir4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, 180, 40));

        jTable1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        jTable1.setModel(modelo
        );
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(22);
        jScrollPane1.setViewportView(jTable1);

        pnlRed.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1000, 420));

        getContentPane().add(pnlRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 1050, 510));

        jPanel1.setBackground(new java.awt.Color(231, 235, 244));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 1050, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCursoActionPerformed
        //TODO add your handling code here:
        
        int pos = cboCurso.getSelectedIndex()-1;
        if(pos>-1){
            c = listaCursos.get(pos);
        }else{
            lblGrado.setText("");
            lblSeccion.setText("");
        }
        try {
            lblGrado.setText(String.valueOf(c.getGrado().getNumGrado()));
            lblSeccion.setText(c.getGrado().getSeccion());
            AlumnoDAO.getInstancia().mostrarListasDocente(c.getGrado().getIdGrado(), modelo);
        } catch(SQLException ex) {
            Logger.getLogger(DialogListasFromDocente.class.getName()).log(Level.SEVERE, null, ex);
        }catch(NullPointerException e){
            System.out.println("NullPointerException capturado en Seleccionar");
        }
        
    }//GEN-LAST:event_cboCursoActionPerformed

    private void btnImprimirMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirMatriculaActionPerformed
        String destino="ListaCurso_SGA"; // nombre por defecto
        JOptionPane.showMessageDialog(this, "Seleccione ubicación de archivo y el nombre respectivo","Guardar Archivo",1);
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showSaveDialog(this);
        cursoSelec = c;
        if(result == JFileChooser.APPROVE_OPTION){
            try {
                destino = fileChooser.getSelectedFile().getCanonicalPath();
                destino+=".pdf";
            } catch (IOException ex) {
                Logger.getLogger(DialogRegistroMatricula.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        // CREACION DEL PDF
        Document document = new Document();
        try {
            PdfWriter.getInstance(document, new FileOutputStream(destino));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DialogRegistroMatricula.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(DialogRegistroMatricula.class.getName()).log(Level.SEVERE, null, ex);
        }
        document.open();
        
        // FUENTES
        Font fontNegrita_1 = new Font(Font.FontFamily.HELVETICA, 22, Font.BOLD);
        Font fontNormal_1 = new Font(Font.FontFamily.HELVETICA, 20, Font.NORMAL);
        Font fontNegrita_2 = new Font(Font.FontFamily.HELVETICA, 16, Font.BOLD);
        Font fontNormal_2 = new Font(Font.FontFamily.HELVETICA, 16, Font.NORMAL);
        Font fontColumnas = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);
        
        // TEXTOS
        Paragraph para1 = new Paragraph("Institucion Educativa Privada", fontNegrita_1);
        para1.setAlignment(Element.ALIGN_CENTER);
        Paragraph para2 = new Paragraph("CEPAS", fontNegrita_1);
        para2.setAlignment(Element.ALIGN_CENTER);
        Paragraph para3 = new Paragraph("Listado de Alumnos",fontNormal_1);
        para3.setAlignment(Element.ALIGN_CENTER);
        
        Image foto = null;
        try {
            foto = Image.getInstance(getClass().getResource("/img/icon_log.png"));
        } catch (Exception ex2) {
            Logger.getLogger(DialogRegistroMatricula.class.getName()).log(Level.SEVERE, null, ex2);
        }
	foto.setAlignment(Chunk.ALIGN_MIDDLE);
        
       
        
        Paragraph para6 = new Paragraph("Docente: ",fontNegrita_2);
        para6.setFont(fontNormal_2);
        para6.add(d.nombreCompleto());
        para6.setFont(fontNegrita_2);
        para6.add("    DNI: ");
        para6.setFont(fontNormal_2);
        para6.add(d.getDni());
        
        Paragraph para7 = new Paragraph("Curso: ",fontNegrita_2);
        para7.setFont(fontNormal_2);
        para7.add(cursoSelec.getNombre());
        
        Paragraph para8 = new Paragraph("ID: ",fontNegrita_2);
        para8.setFont(fontNormal_2);
        para8.add(cursoSelec.getIdCurso());
        
        
        // TABLA CURSOS
       Paragraph para8_2 = new Paragraph("Alumnos: ",fontNegrita_2);
       PdfPTable tabla = new PdfPTable(2);
       try {
            tabla.setTotalWidth(40f);
            tabla.setWidths(new float[]{10f,30f});
        } catch (DocumentException ex) {
            Logger.getLogger(DialogRecordAcademicoFromAlumno.class.getName()).log(Level.SEVERE, null, ex);
        }
       PdfPCell dni = new PdfPCell(new Paragraph("DNI",fontColumnas)); 
       PdfPCell nombre = new PdfPCell(new Paragraph("Apellidos y nombres",fontColumnas));
       dni.setMinimumHeight(18);
       dni.setHorizontalAlignment(Element.ALIGN_CENTER);
       nombre.setHorizontalAlignment(Element.ALIGN_CENTER);
       tabla.addCell(dni);
       tabla.addCell(nombre);
        try {
            la = BimestreDAO.getInstancia().alumnosBimestre_DialogRegistro(cursoSelec.getIdCurso(), 1);
            int n = la.size();
            Alumno temp;
            for (int i=0;i<=n-2;i++){
                for (int j=i+1;j<=n-1;j++){
                    if(la.get(i).getApellido_p().compareTo(la.get(j).getApellido_p())>0){
                        temp = la.get(i);
                        la.set(i, la.get(j));
                        la.set(j,temp);
                      }
                    }
            }
        } catch (SQLException ex) {
            Logger.getLogger(DialogRegistroMatricula.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       int limiteSalto = la.size()>=10? 10:la.size();
       for (int i = 0; i < limiteSalto; i++)
       {
	tabla.addCell(la.get(i).getDni());
        tabla.addCell(la.get(i).apellidosYNombres());
       }
      
       
       //FIRMA
       Paragraph para9 = new Paragraph("____________________    ",fontNormal_2);
       para9.setAlignment(Element.ALIGN_BOTTOM);
       para9.setAlignment(Element.ALIGN_RIGHT);
       Paragraph para10 = new Paragraph("Docente               ",fontNormal_2);
       para10.setAlignment(Element.ALIGN_BOTTOM);
       para10.setAlignment(Element.ALIGN_RIGHT);
       
       
       // Agregar todos los elementos previamente creados
        try {
            document.add(para1);
            document.add(para2);
            document.add(para3);
            document.add(foto);
            document.add(Chunk.NEWLINE);
            document.add(para6);
            document.add(para7);
            document.add(para8);
            document.add(para8_2);
            document.add(new Paragraph("\n"));
            document.add(tabla);
            /// añadir nueva pagina si tiene muchos alumnos
            if(la.size()>=10)
            {
              document.newPage();
              PdfPTable tabla2 = new PdfPTable(2);
                try {
                   tabla2.setTotalWidth(40f);
                    tabla2.setWidths(new float[]{10f,30f});
                } catch (DocumentException ex) {
                      Logger.getLogger(DialogRecordAcademicoFromAlumno.class.getName()).log(Level.SEVERE, null, ex);
                }
              for (int i = 10; i < la.size(); i++)
              {
	         tabla2.addCell(la.get(i).getDni());
                 tabla2.addCell(la.get(i).apellidosYNombres());
              }
              document.add(tabla2);
           
            }
            //FIRMA
            for (int i = 0; i < 4; i++) {
                document.add(Chunk.NEWLINE);
            }
            document.add(para9);
            document.add(para10);
        } catch (DocumentException ex3) {
            Logger.getLogger(DialogRegistroMatricula.class.getName()).log(Level.SEVERE, null, ex3);
        }
        
        // CERRAR DOCUMENTO y su edicion
        document.close();
        
        // ABRIR ARCHIVO
        File objetofile = new File (destino);
        try {
            Desktop.getDesktop().open(objetofile);
        } catch (IOException ex4) {
            Logger.getLogger(DialogRegistroMatricula.class.getName()).log(Level.SEVERE, null, ex4);
        }
    }//GEN-LAST:event_btnImprimirMatriculaActionPerformed

    private void btnSalir4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalir4ActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DialogListasFromDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DialogListasFromDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DialogListasFromDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DialogListasFromDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DialogListasFromDocente dialog = new DialogListasFromDocente();
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimirMatricula;
    private javax.swing.JButton btnSalir4;
    private javax.swing.JComboBox<String> cboCurso;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDocente;
    private javax.swing.JLabel lblGrado;
    private javax.swing.JLabel lblGrado1;
    private javax.swing.JLabel lblSeccion;
    private javax.swing.JPanel pnlRed;
    // End of variables declaration//GEN-END:variables
}
