/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import datos.AlumnoDAO;
import datos.MatriculaDAO;
import entidad.Alumno;
import entidad.Matricula;
import encriptacion.Encriptador;
import java.awt.Color;
import java.security.NoSuchAlgorithmException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Johann
 */
public class DialogAlumnoPerfil extends javax.swing.JDialog {
    Encriptador ENC = Encriptador.getInstancia();
    Alumno a = null;
    Matricula m = null;
    public DialogAlumnoPerfil() {
        super(FrmInicioAlumno.getInstancia(), true);
        initComponents();       
        setLocationRelativeTo(null);
    }
    public void setAlumno(Alumno alumnolog){
        a = alumnolog;
        llenarDatos();
    }
    private void llenarDatos(){
        txtDNI.setText(a.getDni());
        try {
             m = MatriculaDAO.getInstancia().buscarMatriculaPorDniAlumno(a.getDni());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        }
       
        txtGrado.setText(String.valueOf(m.getGrado().getNumGrado()));
        txtSeccion.setText(m.getGrado().getSeccion());
        
        txtApMaterno.setText(a.getApellido_m());
        txtApPaterno.setText(a.getApellido_p());
        txtNombres.setText(a.getNombre());
        txtEdad.setText(String.valueOf(a.getEdad()));
        txtSexo.setText(a.getSexo());
        txtTelefono.setText(a.getTelefono());
        txtFechaNac.setText(a.getFecha_nacimiento());
        
        txtDNIApoderado.setText(a.getApoderado().getDni());
        txtApellidosApoderado.setText(a.getApoderado().getAp_p());
        txtNombreApoderado.setText(a.getApoderado().getNombre());
        txtTelefonoApoderado.setText(a.getApoderado().getTelefono());
    }
    private void limpiar(){
        txtNuevaContraseña.setText("");
    }
    private void activar(){
        txtNuevaContraseña.setEnabled(true);
        txtNuevaContraseña.setEditable(true);
        btnGuardar.setEnabled(true);
        btnCancelar.setEnabled(true);
        txtNuevaContraseña.setBackground(Color.WHITE);
    }
    private void desactivar(){
        txtNuevaContraseña.setEnabled(false);
        txtNuevaContraseña.setEditable(false);
        btnGuardar.setEnabled(false);
        btnCancelar.setEnabled(false);
        txtNuevaContraseña.setBackground(new Color(204,204,204));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtNuevaContraseña = new javax.swing.JTextField();
        btnActualizarC = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtFechaNac = new javax.swing.JTextField();
        txtApPaterno = new javax.swing.JTextField();
        txtApMaterno = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtGrado = new javax.swing.JTextField();
        txtSeccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtTelefonoApoderado = new javax.swing.JTextField();
        txtDNIApoderado = new javax.swing.JTextField();
        txtApellidosApoderado = new javax.swing.JTextField();
        txtNombreApoderado = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(26, 2, 58));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 80, 950));

        jPanel1.setBackground(new java.awt.Color(26, 2, 58));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNuevaContraseña.setEditable(false);
        txtNuevaContraseña.setBackground(new java.awt.Color(204, 204, 204));
        txtNuevaContraseña.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtNuevaContraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNuevaContraseña.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNuevaContraseña.setEnabled(false);
        jPanel1.add(txtNuevaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 260, 40));

        btnActualizarC.setBackground(new java.awt.Color(255, 255, 255));
        btnActualizarC.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        btnActualizarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono-Actualizar.png"))); // NOI18N
        btnActualizarC.setText("Actualizar");
        btnActualizarC.setBorder(null);
        btnActualizarC.setBorderPainted(false);
        btnActualizarC.setOpaque(false);
        btnActualizarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarCActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 130, 40));

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save_37110.png"))); // NOI18N
        btnGuardar.setText(" Guardar Cambios");
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 160, 40));

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-Delete.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 110, 40));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("NUEVA CONTRASEÑA");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("DNI");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        txtDNI.setEditable(false);
        txtDNI.setBackground(new java.awt.Color(255, 255, 255));
        txtDNI.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtDNI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDNI.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 240, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 570, 220));

        jPanel3.setBackground(new java.awt.Color(26, 2, 58));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("NOMBRES");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel27.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("FECHA DE NACIMIENTO");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel29.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("APELLIDO MATERNO");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtFechaNac.setEditable(false);
        txtFechaNac.setBackground(new java.awt.Color(255, 255, 255));
        txtFechaNac.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtFechaNac.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechaNac.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(txtFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 360, 30));

        txtApPaterno.setEditable(false);
        txtApPaterno.setBackground(new java.awt.Color(255, 255, 255));
        txtApPaterno.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtApPaterno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApPaterno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(txtApPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 360, 30));

        txtApMaterno.setEditable(false);
        txtApMaterno.setBackground(new java.awt.Color(255, 255, 255));
        txtApMaterno.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtApMaterno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApMaterno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(txtApMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 360, 30));

        jLabel30.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("SEXO");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel31.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("EDAD");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel32.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("TELÉFONO");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        txtNombres.setEditable(false);
        txtNombres.setBackground(new java.awt.Color(255, 255, 255));
        txtNombres.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtNombres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombres.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 360, 30));

        txtSexo.setEditable(false);
        txtSexo.setBackground(new java.awt.Color(255, 255, 255));
        txtSexo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtSexo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSexo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 360, 30));

        txtEdad.setEditable(false);
        txtEdad.setBackground(new java.awt.Color(255, 255, 255));
        txtEdad.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtEdad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEdad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 360, 30));

        txtTelefono.setEditable(false);
        txtTelefono.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefono.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 360, 30));

        jLabel33.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("APELLIDO PATERNO");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 470, 460));

        jPanel4.setBackground(new java.awt.Color(194, 36, 45));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("SECCIÓN");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel24.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("GRADO");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        txtGrado.setEditable(false);
        txtGrado.setBackground(new java.awt.Color(255, 255, 255));
        txtGrado.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtGrado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGrado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(txtGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 240, 30));

        txtSeccion.setEditable(false);
        txtSeccion.setBackground(new java.awt.Color(255, 255, 255));
        txtSeccion.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtSeccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSeccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(txtSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 80, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 420, 130));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-alumno.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, 70, 70));

        jLabel9.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(25, 0, 58));
        jLabel9.setText("DATOS PERSONALES");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        jLabel10.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(25, 0, 58));
        jLabel10.setText("USUARIO");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jLabel12.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(25, 0, 58));
        jLabel12.setText("DATOS ACADÉMICOS");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, -1, -1));

        jPanel6.setBackground(new java.awt.Color(231, 235, 244));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(25, 0, 58));
        jLabel11.setText("DATOS DEL APODERADO");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, -1, -1));

        jPanel5.setBackground(new java.awt.Color(194, 36, 45));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("TELÉFONO");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel34.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("DNI");
        jPanel5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel35.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("APELLIDOS");
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel36.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("NOMBRES");
        jPanel5.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        txtTelefonoApoderado.setEditable(false);
        txtTelefonoApoderado.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefonoApoderado.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtTelefonoApoderado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefonoApoderado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(txtTelefonoApoderado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 240, 40));

        txtDNIApoderado.setEditable(false);
        txtDNIApoderado.setBackground(new java.awt.Color(255, 255, 255));
        txtDNIApoderado.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtDNIApoderado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDNIApoderado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(txtDNIApoderado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 240, 40));

        txtApellidosApoderado.setEditable(false);
        txtApellidosApoderado.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidosApoderado.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtApellidosApoderado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApellidosApoderado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(txtApellidosApoderado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 240, 40));

        txtNombreApoderado.setEditable(false);
        txtNombreApoderado.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreApoderado.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtNombreApoderado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreApoderado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(txtNombreApoderado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 240, 40));

        jPanel6.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, 410, 290));

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-salir.png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.setBorder(null);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel6.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 660, 120, 50));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 54)); // NOI18N
        jLabel2.setText("FICHA DE DATOS");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 460, 50));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnActualizarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCActionPerformed
        // TODO add your handling code here:
        activar();
        
    }//GEN-LAST:event_btnActualizarCActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String pword = txtNuevaContraseña.getText().trim();
        
        try {
            pword = ENC.SHA256(pword);
            //Alumno al = new Alumno(a.getDni(), pword, a.getNombre(),a.getApellido_p(), a.getApellido_m(), a.getSexo(), a.getEdad(), a.getTelefono(), a.getFecha_nacimiento(), a.getObservacion(), a.getApoderado());
            //AlumnoDAO.getInstancia().actualizarAlumno(a.getDni(),al);
            AlumnoDAO.getInstancia().actualizarPass(a.getDni(), pword);
            
            limpiar();
            desactivar();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        } catch (NoSuchAlgorithmException ex) {
            System.out.println("Error: "+ex.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        desactivar();
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            a = AlumnoDAO.getInstancia().buscarAlumno(a.getDni());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        }
        FrmInicioAlumno.getInstancia().dispose();
        FrmInicioAlumno f = new FrmInicioAlumno();
        f.setAlumnoLog(a);
        f.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DialogAlumnoPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DialogAlumnoPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DialogAlumnoPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DialogAlumnoPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DialogAlumnoPerfil dialog = new DialogAlumnoPerfil(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarC;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txtApMaterno;
    private javax.swing.JTextField txtApPaterno;
    private javax.swing.JTextField txtApellidosApoderado;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDNIApoderado;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFechaNac;
    private javax.swing.JTextField txtGrado;
    private javax.swing.JTextField txtNombreApoderado;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNuevaContraseña;
    private javax.swing.JTextField txtSeccion;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefonoApoderado;
    // End of variables declaration//GEN-END:variables
}
