/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import datos.BimestreDAO;
import datos.CursoDAO;
import entidad.*;
import java.sql.SQLException;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author despa
 */
public class DialogDocenteBimestre extends javax.swing.JDialog {

    Alumno alumno;
    Curso curso;
    Bimestre bimestre;
    Docente docente;
    
    public DialogDocenteBimestre(Alumno alumno, String idCurso, int numero, Docente docente) {
        super(FrmInicioDocente.getInstancia(),true);
        initComponents();
        setLocationRelativeTo(null);
        this.alumno = alumno;
        this.docente = docente;
        try{
            curso = CursoDAO.getInstancia().buscarCurso(idCurso);
            bimestre = BimestreDAO.getInstancia().buscar(alumno.getDni(), idCurso, numero);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "ERROR: "+ e.getMessage(), "error 1111", 0);
        }
        txtDni.setText(alumno.getDni());
        txtIDCurso.setText(idCurso);
        lblBimestre.setText("BIMESTRE "+bimestre.getNumero());
        lblNombreCurso.setText(curso.getNombre());
        txtNombreAlumno.setText(alumno.nombreCompleto());
    }
     
    
    public void limpiarEntradas(){
        
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
        buttonGroup4.clearSelection();
        buttonGroup5.clearSelection();
        buttonGroup6.clearSelection();
        buttonGroup7.clearSelection();
        buttonGroup8.clearSelection();
        txtN1.setText("");
        txtN2.setText("");
        txtN3.setText("");
        txtN4.setText("");
        txtN5.setText("");
        txtN6.setText("");
        txtN7.setText("");
        txtN8.setText("");
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtDni = new javax.swing.JTextField();
        txtIDCurso = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNombreAlumno = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblNota = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        rbF1 = new javax.swing.JRadioButton();
        rbA1 = new javax.swing.JRadioButton();
        rbT1 = new javax.swing.JRadioButton();
        rbA2 = new javax.swing.JRadioButton();
        rbA3 = new javax.swing.JRadioButton();
        rbA4 = new javax.swing.JRadioButton();
        rbA5 = new javax.swing.JRadioButton();
        rbA6 = new javax.swing.JRadioButton();
        rbA7 = new javax.swing.JRadioButton();
        rbA8 = new javax.swing.JRadioButton();
        rbT2 = new javax.swing.JRadioButton();
        rbT3 = new javax.swing.JRadioButton();
        rbT4 = new javax.swing.JRadioButton();
        rbT5 = new javax.swing.JRadioButton();
        rbT6 = new javax.swing.JRadioButton();
        rbT7 = new javax.swing.JRadioButton();
        rbT8 = new javax.swing.JRadioButton();
        rbF2 = new javax.swing.JRadioButton();
        rbF3 = new javax.swing.JRadioButton();
        rbF4 = new javax.swing.JRadioButton();
        rbF5 = new javax.swing.JRadioButton();
        rbF6 = new javax.swing.JRadioButton();
        rbF7 = new javax.swing.JRadioButton();
        rbF8 = new javax.swing.JRadioButton();
        rbFJ7 = new javax.swing.JRadioButton();
        rbFJ8 = new javax.swing.JRadioButton();
        rbFJ6 = new javax.swing.JRadioButton();
        rbFJ5 = new javax.swing.JRadioButton();
        rbFJ4 = new javax.swing.JRadioButton();
        rbFJ3 = new javax.swing.JRadioButton();
        rbFJ2 = new javax.swing.JRadioButton();
        rbFJ1 = new javax.swing.JRadioButton();
        lblNota1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtN1 = new javax.swing.JTextField();
        txtN2 = new javax.swing.JTextField();
        txtN3 = new javax.swing.JTextField();
        txtN4 = new javax.swing.JTextField();
        txtN5 = new javax.swing.JTextField();
        txtN6 = new javax.swing.JTextField();
        txtN7 = new javax.swing.JTextField();
        txtN8 = new javax.swing.JTextField();
        lblfecha1 = new javax.swing.JLabel();
        lblfecha2 = new javax.swing.JLabel();
        lblfecha3 = new javax.swing.JLabel();
        lblfecha4 = new javax.swing.JLabel();
        lblfecha5 = new javax.swing.JLabel();
        lblfecha6 = new javax.swing.JLabel();
        lblfecha7 = new javax.swing.JLabel();
        lblfecha9 = new javax.swing.JLabel();
        btnRestaurar = new javax.swing.JButton();
        pnlSide = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblBimestre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblNombreCurso = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(26, 2, 58));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDni.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtDni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDni.setBorder(null);
        txtDni.setEnabled(false);
        jPanel1.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 210, 50));

        txtIDCurso.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtIDCurso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIDCurso.setBorder(null);
        txtIDCurso.setEnabled(false);
        txtIDCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDCursoActionPerformed(evt);
            }
        });
        jPanel1.add(txtIDCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 160, 50));

        jLabel11.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("NOMBRE COMPLETO");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        jLabel13.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ID DE CURSO");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel14.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("DNI DE ESTUDIANTE");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        txtNombreAlumno.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtNombreAlumno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreAlumno.setBorder(null);
        txtNombreAlumno.setEnabled(false);
        jPanel1.add(txtNombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 310, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 810, 110));

        jPanel2.setBackground(new java.awt.Color(194, 36, 45));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNota.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblNota.setForeground(new java.awt.Color(255, 255, 255));
        lblNota.setText("Nota");
        jPanel2.add(lblNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(rbF1);
        rbF1.setText("Falta");
        rbF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbF1ActionPerformed(evt);
            }
        });
        jPanel4.add(rbF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, 30));

        buttonGroup1.add(rbA1);
        rbA1.setText("Presente");
        jPanel4.add(rbA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        buttonGroup1.add(rbT1);
        rbT1.setText("Tardanza");
        jPanel4.add(rbT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, 30));

        buttonGroup2.add(rbA2);
        rbA2.setText("Presente");
        jPanel4.add(rbA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 30));

        buttonGroup3.add(rbA3);
        rbA3.setText("Presente");
        jPanel4.add(rbA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 30));

        buttonGroup4.add(rbA4);
        rbA4.setText("Presente");
        jPanel4.add(rbA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));

        buttonGroup5.add(rbA5);
        rbA5.setText("Presente");
        jPanel4.add(rbA5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 30));

        buttonGroup6.add(rbA6);
        rbA6.setText("Presente");
        jPanel4.add(rbA6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 30));

        buttonGroup7.add(rbA7);
        rbA7.setText("Presente");
        jPanel4.add(rbA7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 30));

        buttonGroup8.add(rbA8);
        rbA8.setText("Presente");
        jPanel4.add(rbA8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 30));

        buttonGroup2.add(rbT2);
        rbT2.setText("Tardanza");
        jPanel4.add(rbT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, 30));

        buttonGroup3.add(rbT3);
        rbT3.setText("Tardanza");
        jPanel4.add(rbT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, 30));

        buttonGroup4.add(rbT4);
        rbT4.setText("Tardanza");
        jPanel4.add(rbT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, 30));

        buttonGroup5.add(rbT5);
        rbT5.setText("Tardanza");
        jPanel4.add(rbT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, 30));

        buttonGroup6.add(rbT6);
        rbT6.setText("Tardanza");
        jPanel4.add(rbT6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, 30));

        buttonGroup7.add(rbT7);
        rbT7.setText("Tardanza");
        jPanel4.add(rbT7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, 30));

        buttonGroup8.add(rbT8);
        rbT8.setText("Tardanza");
        jPanel4.add(rbT8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, 30));

        buttonGroup2.add(rbF2);
        rbF2.setText("Falta");
        rbF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbF2ActionPerformed(evt);
            }
        });
        jPanel4.add(rbF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, 30));

        buttonGroup3.add(rbF3);
        rbF3.setText("Falta");
        rbF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbF3ActionPerformed(evt);
            }
        });
        jPanel4.add(rbF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, 30));

        buttonGroup4.add(rbF4);
        rbF4.setText("Falta");
        rbF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbF4ActionPerformed(evt);
            }
        });
        jPanel4.add(rbF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, 30));

        buttonGroup5.add(rbF5);
        rbF5.setText("Falta");
        rbF5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbF5ActionPerformed(evt);
            }
        });
        jPanel4.add(rbF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, 30));

        buttonGroup6.add(rbF6);
        rbF6.setText("Falta");
        rbF6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbF6ActionPerformed(evt);
            }
        });
        jPanel4.add(rbF6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, 30));

        buttonGroup7.add(rbF7);
        rbF7.setText("Falta");
        rbF7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbF7ActionPerformed(evt);
            }
        });
        jPanel4.add(rbF7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, 30));

        buttonGroup8.add(rbF8);
        rbF8.setText("Falta");
        rbF8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbF8ActionPerformed(evt);
            }
        });
        jPanel4.add(rbF8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, 30));

        buttonGroup7.add(rbFJ7);
        rbFJ7.setText("Falta Justificada");
        rbFJ7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFJ7ActionPerformed(evt);
            }
        });
        jPanel4.add(rbFJ7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, 30));

        buttonGroup8.add(rbFJ8);
        rbFJ8.setText("Falta Justificada");
        rbFJ8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFJ8ActionPerformed(evt);
            }
        });
        jPanel4.add(rbFJ8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, 30));

        buttonGroup6.add(rbFJ6);
        rbFJ6.setText("Falta Justificada");
        rbFJ6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFJ6ActionPerformed(evt);
            }
        });
        jPanel4.add(rbFJ6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, 30));

        buttonGroup5.add(rbFJ5);
        rbFJ5.setText("Falta Justificada");
        rbFJ5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFJ5ActionPerformed(evt);
            }
        });
        jPanel4.add(rbFJ5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, 30));

        buttonGroup4.add(rbFJ4);
        rbFJ4.setText("Falta Justificada");
        rbFJ4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFJ4ActionPerformed(evt);
            }
        });
        jPanel4.add(rbFJ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, 30));

        buttonGroup3.add(rbFJ3);
        rbFJ3.setText("Falta Justificada");
        rbFJ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFJ3ActionPerformed(evt);
            }
        });
        jPanel4.add(rbFJ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, 30));

        buttonGroup2.add(rbFJ2);
        rbFJ2.setText("Falta Justificada");
        rbFJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFJ2ActionPerformed(evt);
            }
        });
        jPanel4.add(rbFJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, 30));

        buttonGroup1.add(rbFJ1);
        rbFJ1.setText("Falta Justificada");
        rbFJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFJ1ActionPerformed(evt);
            }
        });
        jPanel4.add(rbFJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 510, 350));

        lblNota1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblNota1.setForeground(new java.awt.Color(255, 255, 255));
        lblNota1.setText("Asistencia");
        jPanel2.add(lblNota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtN1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtN1KeyTyped(evt);
            }
        });
        jPanel5.add(txtN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 30));

        txtN2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtN2KeyTyped(evt);
            }
        });
        jPanel5.add(txtN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 30));

        txtN3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtN3KeyTyped(evt);
            }
        });
        jPanel5.add(txtN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 50, 30));

        txtN4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtN4KeyTyped(evt);
            }
        });
        jPanel5.add(txtN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 50, 30));

        txtN5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtN5KeyTyped(evt);
            }
        });
        jPanel5.add(txtN5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 50, 30));

        txtN6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtN6KeyTyped(evt);
            }
        });
        jPanel5.add(txtN6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 50, 30));

        txtN7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtN7KeyTyped(evt);
            }
        });
        jPanel5.add(txtN7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 50, 30));

        txtN8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtN8KeyTyped(evt);
            }
        });
        jPanel5.add(txtN8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 50, 30));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 70, 350));

        lblfecha1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblfecha1.setForeground(new java.awt.Color(255, 255, 255));
        lblfecha1.setText("Semana 1");
        jPanel2.add(lblfecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 30));

        lblfecha2.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblfecha2.setForeground(new java.awt.Color(255, 255, 255));
        lblfecha2.setText("Semana 2");
        jPanel2.add(lblfecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));

        lblfecha3.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblfecha3.setForeground(new java.awt.Color(255, 255, 255));
        lblfecha3.setText("Semana 3");
        jPanel2.add(lblfecha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 30));

        lblfecha4.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblfecha4.setForeground(new java.awt.Color(255, 255, 255));
        lblfecha4.setText("Semana 4");
        jPanel2.add(lblfecha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 30));

        lblfecha5.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblfecha5.setForeground(new java.awt.Color(255, 255, 255));
        lblfecha5.setText("Semana 5");
        jPanel2.add(lblfecha5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 30));

        lblfecha6.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblfecha6.setForeground(new java.awt.Color(255, 255, 255));
        lblfecha6.setText("Semana 6");
        jPanel2.add(lblfecha6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 30));

        lblfecha7.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblfecha7.setForeground(new java.awt.Color(255, 255, 255));
        lblfecha7.setText("Semana 7");
        jPanel2.add(lblfecha7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, 30));

        lblfecha9.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblfecha9.setForeground(new java.awt.Color(255, 255, 255));
        lblfecha9.setText("Semana 8");
        jPanel2.add(lblfecha9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 940, 420));

        btnRestaurar.setBackground(new java.awt.Color(153, 255, 204));
        btnRestaurar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRestaurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-clean.png"))); // NOI18N
        btnRestaurar.setText("Restaurar");
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRestaurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 760, 150, 50));

        pnlSide.setBackground(new java.awt.Color(26, 2, 58));

        javax.swing.GroupLayout pnlSideLayout = new javax.swing.GroupLayout(pnlSide);
        pnlSide.setLayout(pnlSideLayout);
        pnlSideLayout.setHorizontalGroup(
            pnlSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlSideLayout.setVerticalGroup(
            pnlSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );

        getContentPane().add(pnlSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 840));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 54)); // NOI18N
        jLabel3.setText("REGISTRO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 300, 50));

        lblBimestre.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lblBimestre.setForeground(new java.awt.Color(25, 0, 58));
        getContentPane().add(lblBimestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 200, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_calificaciones.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 70, 70));

        jLabel15.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(25, 0, 58));
        jLabel15.setText("DETALLE DE CURSO Y ESTUDIANTE");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        lblNombreCurso.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        getContentPane().add(lblNombreCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 650, 30));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save_37110.png"))); // NOI18N
        btnGuardar.setText("Registrar");
        btnGuardar.setBorder(null);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 760, 150, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        limpiarEntradas();
    }//GEN-LAST:event_btnRestaurarActionPerformed

    private void validarNotas(double n1, double n2, double n3, double n4, double n5, double n6, double n7, double n8) throws IllegalArgumentException{
        double notas[]={n1, n2, n3, n4, n5, n6, n7, n8};
        for(double e: notas){
            if(e<0 || e>20)
                throw new IllegalArgumentException();
        }
    }
    
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // Asistencia: 3, Tardanza: 2, Falta justificada: 1, Falta: 0
        try{
            double n1=Double.parseDouble(txtN1.getText());
            double n2=Double.parseDouble(txtN2.getText());
            double n3=Double.parseDouble(txtN3.getText());
            double n4=Double.parseDouble(txtN4.getText());
            double n5=Double.parseDouble(txtN5.getText());
            double n6=Double.parseDouble(txtN6.getText());
            double n7=Double.parseDouble(txtN7.getText());
            double n8=Double.parseDouble(txtN8.getText());
            
            validarNotas(n1, n2, n3, n4, n5, n6, n7, n8);
            
            String a1="",a2="",a3="",a4="",a5="",a6="",a7="",a8="";
            if (rbA1.isSelected())
                a1="3";
            else
                if (rbT1.isSelected())
                    a1="2";
                else
                    if(rbFJ1.isSelected())
                        a1="1";
                    else
                        if(rbF1.isSelected())
                            a1="0";

            if (rbA2.isSelected())
                a2="3";
            else
                if (rbT2.isSelected())
                    a2="2";
                else
                    if(rbFJ2.isSelected())
                        a2="1";
                    else
                        if(rbF2.isSelected())
                            a2="0";

            if (rbA3.isSelected())
                a3="3";
            else
                if (rbT3.isSelected())
                    a3="2";
                else
                    if(rbFJ3.isSelected())
                        a3="1";
                    else
                        if(rbF3.isSelected())
                            a3="0";

            if (rbA4.isSelected())
                a4="3";
            else
                if (rbT4.isSelected())
                    a4="2";
                else
                    if(rbFJ4.isSelected())
                        a4="1";
                    else
                        if(rbF4.isSelected())
                            a4="0";

            if (rbA5.isSelected())
                a5="3";
            else
                if (rbT5.isSelected())
                    a5="2";
                else
                    if(rbFJ5.isSelected())
                        a5="1";
                    else
                        if(rbF5.isSelected())
                            a5="0";

            if (rbA6.isSelected())
                a6="3";
            else
                if (rbT6.isSelected())
                    a6="2";
                else
                    if(rbFJ6.isSelected())
                        a6="1";
                    else
                        if(rbF6.isSelected())
                            a6="0";

            if (rbA7.isSelected())
                a7="3";
            else
                if (rbT7.isSelected())
                    a7="2";
                else
                    if(rbFJ7.isSelected())
                        a7="1";
                    else
                        if(rbF7.isSelected())
                            a7="0";

            if (rbA8.isSelected())
                a8="3";
            else
                if (rbT8.isSelected())
                    a8="2";
                else
                    if(rbFJ8.isSelected())
                        a8="1";
                    else
                        if(rbF8.isSelected())
                            a8="0";
            String asistencia_binaria="";
            asistencia_binaria+=a1+a2+a3+a4+a5+a6+a7+a8;
            Bimestre bimestreNuevo = new Bimestre(curso, bimestre.getNumero(), n1, n2, n3, n4, n5, n6, n7, n8, asistencia_binaria);
            try {
                BimestreDAO.getInstancia().actualizar(bimestreNuevo, alumno);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"ERROR:"+ex.getMessage());
            }
            DialogRegistro dReg = new DialogRegistro(docente);
            dReg.mostrarTabla(dReg.modelo);
            this.dispose();
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(null, "Notas ingresadas presentan valores inválidos. \nRevisar que la nota este entre 0 y 20", "Advertencia", 2);
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void rbF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbF1ActionPerformed

    }//GEN-LAST:event_rbF1ActionPerformed

    private void rbFJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFJ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFJ1ActionPerformed

    private void rbF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbF2ActionPerformed

    private void rbF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbF3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbF3ActionPerformed

    private void rbF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbF4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbF4ActionPerformed

    private void rbF5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbF5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbF5ActionPerformed

    private void rbF6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbF6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbF6ActionPerformed

    private void rbF7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbF7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbF7ActionPerformed

    private void rbF8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbF8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbF8ActionPerformed

    private void rbFJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFJ2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFJ2ActionPerformed

    private void rbFJ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFJ3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFJ3ActionPerformed

    private void rbFJ4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFJ4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFJ4ActionPerformed

    private void rbFJ5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFJ5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFJ5ActionPerformed

    private void rbFJ6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFJ6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFJ6ActionPerformed

    private void rbFJ7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFJ7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFJ7ActionPerformed

    private void rbFJ8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFJ8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFJ8ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        // Asistencia: 3, Tardanza: 2, Falta justificada: 1, Falta: 0
        String asistenciaBinaria = bimestre.getAsistencia_binaria();
       
            if (asistenciaBinaria.substring(0,1).equals("3")) {
                rbA1.setSelected(true);
            } else if (asistenciaBinaria.substring(0,1).equals("2")) {
                rbT1.setSelected(true);
            } else if (asistenciaBinaria.substring(0,1).equals("1")) {
                rbFJ1.setSelected(true);
            } else if (asistenciaBinaria.substring(0,1).equals("0")) {
                rbF1.setSelected(true);
            }
            
            if (asistenciaBinaria.substring(1,2).equals("3")) {
                rbA2.setSelected(true);
            } else if (asistenciaBinaria.substring(1,2).equals("2")) {
                rbT2.setSelected(true);
            } else if (asistenciaBinaria.substring(1,2).equals("1")) {
                rbFJ2.setSelected(true);
            } else if (asistenciaBinaria.substring(1,2).equals("0")) {
                rbF2.setSelected(true);
            }
            if (asistenciaBinaria.substring(0,1).equals("3")) {
                rbA3.setSelected(true);
            } else if (asistenciaBinaria.substring(2,3).equals("2")) {
                rbT3.setSelected(true);
            } else if (asistenciaBinaria.substring(2,3).equals("1")) {
                rbFJ3.setSelected(true);
            } else if (asistenciaBinaria.substring(2,3).equals("0")) {
                rbF3.setSelected(true);
            }
           if (asistenciaBinaria.substring(3,4).equals("3")) {
                rbA4.setSelected(true);
            } else if (asistenciaBinaria.substring(3,4).equals("2")) {
                rbT4.setSelected(true);
            } else if (asistenciaBinaria.substring(3,4).equals("1")) {
                rbFJ4.setSelected(true);
            } else if (asistenciaBinaria.substring(3,4).equals("0")) {
                rbF4.setSelected(true);
            }
           if (asistenciaBinaria.substring(4,5).equals("3")) {
                rbA5.setSelected(true);
            } else if (asistenciaBinaria.substring(4,5).equals("2")) {
                rbT5.setSelected(true);
            } else if (asistenciaBinaria.substring(4,5).equals("1")) {
                rbFJ5.setSelected(true);
            } else if (asistenciaBinaria.substring(4,5).equals("0")) {
                rbF5.setSelected(true);
            }
            if (asistenciaBinaria.substring(5,6).equals("3")) {
                rbA6.setSelected(true);
            } else if (asistenciaBinaria.substring(5,6).equals("2")) {
                rbT6.setSelected(true);
            } else if (asistenciaBinaria.substring(5,6).equals("1")) {
                rbFJ6.setSelected(true);
            } else if (asistenciaBinaria.substring(5,6).equals("0")) {
                rbF6.setSelected(true);
            }
            if (asistenciaBinaria.substring(6,7).equals("3")) {
                rbA7.setSelected(true);
            } else if (asistenciaBinaria.substring(6,7).equals("2")) {
                rbT7.setSelected(true);
            } else if (asistenciaBinaria.substring(6,7).equals("1")) {
                rbFJ7.setSelected(true);
            } else if (asistenciaBinaria.substring(6,7).equals("0")) {
                rbF7.setSelected(true);
            }
            if (asistenciaBinaria.substring(7,8).equals("3")) {
                rbA8.setSelected(true);
            } else if (asistenciaBinaria.substring(7,8).equals("2")) {
                rbT8.setSelected(true);
            } else if (asistenciaBinaria.substring(7,8).equals("1")) {
                rbFJ8.setSelected(true);
            } else if (asistenciaBinaria.substring(7,8).equals("0")) {
                rbF8.setSelected(true);
            }
        
        txtN1.setText(String.format(Locale.US,"%.2f",bimestre.getN1()));
        txtN2.setText(String.format(Locale.US,"%.2f",bimestre.getN2()));
        txtN3.setText(String.format(Locale.US,"%.2f",bimestre.getN3()));
        txtN4.setText(String.format(Locale.US,"%.2f",bimestre.getN4()));
        txtN5.setText(String.format(Locale.US,"%.2f",bimestre.getN5()));
        txtN6.setText(String.format(Locale.US,"%.2f",bimestre.getN6()));
        txtN7.setText(String.format(Locale.US,"%.2f",bimestre.getN7()));
        txtN8.setText(String.format(Locale.US,"%.2f",bimestre.getN8()));
    }//GEN-LAST:event_formWindowOpened

    private void txtIDCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDCursoActionPerformed

    private void txtN1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtN1KeyTyped
        char c=evt.getKeyChar();
        int punto=txtN1.getText().indexOf(".")+1;
        if(punto==0){
            if(!Character.isDigit(c) && c!='.')
               evt.consume();
        }
        else{
              if(!Character.isDigit(c))
                 evt.consume();
            }
    }//GEN-LAST:event_txtN1KeyTyped

    private void txtN2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtN2KeyTyped
        char c=evt.getKeyChar();
        int punto=txtN2.getText().indexOf(".")+1;
        if(punto==0){
            if(!Character.isDigit(c) && c!='.')
               evt.consume();
        }
        else{
              if(!Character.isDigit(c))
                 evt.consume();
            }
    }//GEN-LAST:event_txtN2KeyTyped

    private void txtN3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtN3KeyTyped
        char c=evt.getKeyChar();
        int punto=txtN3.getText().indexOf(".")+1;
        if(punto==0){
            if(!Character.isDigit(c) && c!='.')
               evt.consume();
        }
        else{
              if(!Character.isDigit(c))
                 evt.consume();
            }
    }//GEN-LAST:event_txtN3KeyTyped

    private void txtN4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtN4KeyTyped
        char c=evt.getKeyChar();
        int punto=txtN4.getText().indexOf(".")+1;
        if(punto==0){
            if(!Character.isDigit(c) && c!='.')
               evt.consume();
        }
        else{
              if(!Character.isDigit(c))
                 evt.consume();
            }
    }//GEN-LAST:event_txtN4KeyTyped

    private void txtN5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtN5KeyTyped
        char c=evt.getKeyChar();
        int punto=txtN5.getText().indexOf(".")+1;
        if(punto==0){
            if(!Character.isDigit(c) && c!='.')
               evt.consume();
        }
        else{
              if(!Character.isDigit(c))
                 evt.consume();
            }
    }//GEN-LAST:event_txtN5KeyTyped

    private void txtN6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtN6KeyTyped
        char c=evt.getKeyChar();
        int punto=txtN6.getText().indexOf(".")+1;
        if(punto==0){
            if(!Character.isDigit(c) && c!='.')
               evt.consume();
        }
        else{
              if(!Character.isDigit(c))
                 evt.consume();
            }
    }//GEN-LAST:event_txtN6KeyTyped

    private void txtN7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtN7KeyTyped
        char c=evt.getKeyChar();
        int punto=txtN7.getText().indexOf(".")+1;
        if(punto==0){
            if(!Character.isDigit(c) && c!='.')
               evt.consume();
        }
        else{
              if(!Character.isDigit(c))
                 evt.consume();
            }
    }//GEN-LAST:event_txtN7KeyTyped

    private void txtN8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtN8KeyTyped
        char c=evt.getKeyChar();
        int punto=txtN8.getText().indexOf(".")+1;
        if(punto==0){
            if(!Character.isDigit(c) && c!='.')
               evt.consume();
        }
        else{
              if(!Character.isDigit(c))
                 evt.consume();
            }
    }//GEN-LAST:event_txtN8KeyTyped

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DialogDocenteBimestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DialogDocenteBimestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DialogDocenteBimestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DialogDocenteBimestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DialogDocenteBimestre dialog = new DialogDocenteBimestre(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblBimestre;
    private javax.swing.JLabel lblNombreCurso;
    private javax.swing.JLabel lblNota;
    private javax.swing.JLabel lblNota1;
    private javax.swing.JLabel lblfecha1;
    private javax.swing.JLabel lblfecha2;
    private javax.swing.JLabel lblfecha3;
    private javax.swing.JLabel lblfecha4;
    private javax.swing.JLabel lblfecha5;
    private javax.swing.JLabel lblfecha6;
    private javax.swing.JLabel lblfecha7;
    private javax.swing.JLabel lblfecha9;
    private javax.swing.JPanel pnlSide;
    private javax.swing.JRadioButton rbA1;
    private javax.swing.JRadioButton rbA2;
    private javax.swing.JRadioButton rbA3;
    private javax.swing.JRadioButton rbA4;
    private javax.swing.JRadioButton rbA5;
    private javax.swing.JRadioButton rbA6;
    private javax.swing.JRadioButton rbA7;
    private javax.swing.JRadioButton rbA8;
    private javax.swing.JRadioButton rbF1;
    private javax.swing.JRadioButton rbF2;
    private javax.swing.JRadioButton rbF3;
    private javax.swing.JRadioButton rbF4;
    private javax.swing.JRadioButton rbF5;
    private javax.swing.JRadioButton rbF6;
    private javax.swing.JRadioButton rbF7;
    private javax.swing.JRadioButton rbF8;
    private javax.swing.JRadioButton rbFJ1;
    private javax.swing.JRadioButton rbFJ2;
    private javax.swing.JRadioButton rbFJ3;
    private javax.swing.JRadioButton rbFJ4;
    private javax.swing.JRadioButton rbFJ5;
    private javax.swing.JRadioButton rbFJ6;
    private javax.swing.JRadioButton rbFJ7;
    private javax.swing.JRadioButton rbFJ8;
    private javax.swing.JRadioButton rbT1;
    private javax.swing.JRadioButton rbT2;
    private javax.swing.JRadioButton rbT3;
    private javax.swing.JRadioButton rbT4;
    private javax.swing.JRadioButton rbT5;
    private javax.swing.JRadioButton rbT6;
    private javax.swing.JRadioButton rbT7;
    private javax.swing.JRadioButton rbT8;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtIDCurso;
    private javax.swing.JTextField txtN1;
    private javax.swing.JTextField txtN2;
    private javax.swing.JTextField txtN3;
    private javax.swing.JTextField txtN4;
    private javax.swing.JTextField txtN5;
    private javax.swing.JTextField txtN6;
    private javax.swing.JTextField txtN7;
    private javax.swing.JTextField txtN8;
    private javax.swing.JTextField txtNombreAlumno;
    // End of variables declaration//GEN-END:variables
}
