/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;
import datos.ApoderadoDAO;
import datos.DocenteDAO;
import datos.UsuarioDAO;
import entidad.Docente;
import encriptacion.Encriptador;
import java.awt.Cursor;
import java.security.NoSuchAlgorithmException;
import java.text.*;
import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Johann
 */
public class DialogDocentes extends javax.swing.JDialog {

    DefaultTableModel modelo = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    Docente docenteSelec = null;
    Docente docenteBusc = null;
    DocenteDAO d = DocenteDAO.getInstancia();
    Encriptador ENC = Encriptador.getInstancia();
    
    private static DialogDocentes instancia;
     public static DialogDocentes getInstancia(){
        if(instancia==null)
            instancia=new DialogDocentes();
        return instancia;
    }
    public DialogDocentes() {
        super(FrmInicioSecretaria.getInstancia(),true);
        initComponents();
        setLocationRelativeTo(null);
      
        
        try {
            DocenteDAO.getInstancia().mostrar(DocenteDAO.getInstancia().mostrarDocentes(), modelo);    
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        }
        
        SpinnerNumberModel nm = new SpinnerNumberModel();
        nm.setMaximum(65);
        nm.setMinimum(20);
        nm.setValue(35);
        spnnrEdad.setModel(nm);
        btnReestablecer.setVisible(false);
    }
    
    public void setB(boolean b){ 
        if(b){ 
           btnSeleccionar.setVisible(b); 
        }else btnSeleccionar.setVisible(b);  
    }
    
    public void setScaledPhoto(JLabel lbl, String route){
        ImageIcon img = new ImageIcon(route);
        Icon icono = new ImageIcon(img.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), 1));
        lbl.setIcon(icono);
    }
    
     private void activar(){
        btnActualizar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnActualizar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnEliminar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        btnRegistrar.setEnabled(false);
        btnConsultar.setEnabled(false);
        
        btnReestablecer.setVisible(true);
        
        btnRegistrar.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        btnConsultar.setCursor(new Cursor(Cursor.WAIT_CURSOR));
    }
    private void desactivar(){
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnActualizar.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        btnEliminar.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        
        btnRegistrar.setEnabled(true);
        btnConsultar.setEnabled(true);
        
        btnReestablecer.setVisible(false);
        
        btnRegistrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnConsultar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
    
    private void limpiar(){
        txtApellidoMat.setText("");
        txtApellidoPat.setText("");
        txtDNI.setText("");
        spnnrEdad.setValue(35);
        txtNombre.setText("");
        txtSueldo.setText("");
        txtTelefono.setText("");
        jdFechaNac.setDate(null);
        txtDNI.requestFocus();
        btnReestablecer.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlBack = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtBuscDNI = new javax.swing.JTextField();
        cboOrdenar = new javax.swing.JComboBox<>();
        btnSeleccionar = new javax.swing.JButton();
        btnEliminarEnTabla = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtDNI = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnReestablecer = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtApellidoPat = new javax.swing.JTextField();
        txtApellidoMat = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtSueldo = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        rbtnM = new javax.swing.JRadioButton();
        rbtnF = new javax.swing.JRadioButton();
        jdFechaNac = new com.toedter.calendar.JDateChooser();
        spnnrEdad = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(null);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBack.setBackground(new java.awt.Color(231, 235, 244));
        pnlBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 0, 58));
        jLabel1.setText("Información Personal");
        pnlBack.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, -1, -1));

        jPanel2.setBackground(new java.awt.Color(26, 2, 58));
        pnlBack.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 80, 950));

        jPanel6.setBackground(new java.awt.Color(196, 36, 45));
        pnlBack.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 190, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/docente_icono.png"))); // NOI18N
        pnlBack.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 54)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(25, 0, 58));
        jLabel2.setText("DOCENTES");
        pnlBack.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, 70));

        jPanel1.setBackground(new java.awt.Color(194, 36, 45));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        jTable1.setModel(modelo);
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(22);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1420, 360));

        txtBuscDNI.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        txtBuscDNI.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtBuscDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscDNIKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscDNIKeyTyped(evt);
            }
        });
        jPanel1.add(txtBuscDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 220, 30));

        cboOrdenar.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        cboOrdenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "NOMBRE", "APELLIDO PATERNO", "APELLIDO MATERNO", "EDAD", "FECHA DE NACIMIENTO", "SUELDO" }));
        cboOrdenar.setBorder(null);
        cboOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboOrdenarActionPerformed(evt);
            }
        });
        jPanel1.add(cboOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 150, 40));

        btnSeleccionar.setBackground(new java.awt.Color(255, 255, 255));
        btnSeleccionar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-selecc.png"))); // NOI18N
        btnSeleccionar.setText("SELECCIONAR");
        btnSeleccionar.setBorder(null);
        btnSeleccionar.setBorderPainted(false);
        btnSeleccionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeleccionar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 220, 40));

        btnEliminarEnTabla.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminarEnTabla.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnEliminarEnTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-Delete.png"))); // NOI18N
        btnEliminarEnTabla.setText("ELIMINAR");
        btnEliminarEnTabla.setBorder(null);
        btnEliminarEnTabla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarEnTabla.setFocusPainted(false);
        btnEliminarEnTabla.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEliminarEnTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEnTablaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarEnTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 190, 40));

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ordenar");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Buscar por DNI");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        pnlBack.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 1490, 470));

        btnLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-clean.png"))); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorder(null);
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        pnlBack.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 220, 180, 50));

        jLabel6.setFont(new java.awt.Font("Yu Gothic Medium", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(25, 0, 58));
        jLabel6.setText("Registro");
        pnlBack.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, 70));

        jPanel3.setBackground(new java.awt.Color(26, 2, 58));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDNI.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        txtDNI.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDNIKeyTyped(evt);
            }
        });
        jPanel3.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 30));

        jLabel11.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DNI");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnReestablecer.setBackground(new java.awt.Color(255, 255, 255));
        btnReestablecer.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        btnReestablecer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-key.png"))); // NOI18N
        btnReestablecer.setText("Reestablecer contraseña");
        btnReestablecer.setBorder(null);
        btnReestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReestablecerActionPerformed(evt);
            }
        });
        jPanel3.add(btnReestablecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 260, 50));

        pnlBack.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 490, 80));

        jLabel9.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(25, 0, 58));
        jLabel9.setText("Usuario");
        pnlBack.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        btnRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save_37110.png"))); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setBorder(null);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        pnlBack.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 50, 150, 60));

        btnActualizar.setBackground(new java.awt.Color(255, 255, 255));
        btnActualizar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono-Actualizar.png"))); // NOI18N
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setBorder(null);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnActualizar.setEnabled(false);
        btnActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        pnlBack.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 140, 150, 60));

        btnConsultar.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono-Consulta.png"))); // NOI18N
        btnConsultar.setText("CONSULTAR");
        btnConsultar.setBorder(null);
        btnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        pnlBack.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 50, 150, 60));

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono-Eliminar.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorder(null);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnEliminar.setEnabled(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        pnlBack.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 140, 150, 60));

        jPanel4.setBackground(new java.awt.Color(26, 2, 58));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtApellidoPat.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        txtApellidoPat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(txtApellidoPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 210, -1));

        txtApellidoMat.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        txtApellidoMat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtApellidoMat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoMatKeyTyped(evt);
            }
        });
        jPanel4.add(txtApellidoMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 200, -1));

        txtNombre.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 210, -1));

        txtTelefono.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        txtTelefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel4.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 140, -1));

        txtSueldo.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        txtSueldo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSueldoActionPerformed(evt);
            }
        });
        txtSueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSueldoKeyTyped(evt);
            }
        });
        jPanel4.add(txtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 110, 20));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbtnM.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbtnM);
        rbtnM.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        rbtnM.setText("MASCULINO");
        jPanel5.add(rbtnM, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        rbtnF.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbtnF);
        rbtnF.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        rbtnF.setText("FEMENINO");
        jPanel5.add(rbtnF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 140, 60));

        jdFechaNac.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jdFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 160, 30));

        spnnrEdad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(spnnrEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SEXO");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TELÉFONO");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        jLabel12.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("APELLIDO PATERNO");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel13.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("APELLIDO MATERNO");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel14.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("FECHA DE NACIMIENTO");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        jLabel15.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("NOMBRES");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel16.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("S/");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        jLabel17.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("EDAD");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel18.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("SUELDO");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        pnlBack.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 620, 210));

        getContentPane().add(pnlBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarEnTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEnTablaActionPerformed
        // TODO add your handling code here:
      
        try {
            int i = jTable1.getSelectedRow();
            if (i != -1) {
                String iddocente = modelo.getValueAt(i, 0).toString();
                Docente dx = DocenteDAO.getInstancia().buscarDocente(iddocente);
                DocenteDAO.getInstancia().eliminar(dx.getDni());
                DocenteDAO.getInstancia().mostrar(DocenteDAO.getInstancia().mostrarDocentes(), modelo);  
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione un elemento", "", 2);
            }
        } catch (SQLException e) {
             JOptionPane.showMessageDialog(null, "Acción restringida: No se puede eliminar un docente que enseña en un curso donde hay\nalumnos matriculados", "Advertencia", 0);
        }
        
    }//GEN-LAST:event_btnEliminarEnTablaActionPerformed

    private void txtBuscDNIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscDNIKeyReleased
        // TODO add your handling code here:
        
        try {
            if(txtBuscDNI.getText().equals(""))
                 DocenteDAO.getInstancia().mostrar(DocenteDAO.getInstancia().mostrarDocentes(), modelo);  
            else
                DocenteDAO.getInstancia().mostrar(DocenteDAO.getInstancia().buscarPorID(txtBuscDNI.getText().trim()),modelo);
        } catch(DataTruncation e){
            
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage(),"",0);
        }
    }//GEN-LAST:event_txtBuscDNIKeyReleased

    private void cboOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboOrdenarActionPerformed
        // TODO add your handling code here:
         try {
            switch(cboOrdenar.getSelectedIndex()){
                case 0: DocenteDAO.getInstancia().mostrar(DocenteDAO.getInstancia().mostrarDocentes(), modelo); break;
                case 1: DocenteDAO.getInstancia().mostrar(DocenteDAO.getInstancia().ordenar("nombre"), modelo); break;
                case 2: DocenteDAO.getInstancia().mostrar(DocenteDAO.getInstancia().ordenar("ap_p"), modelo); break;
                case 3: DocenteDAO.getInstancia().mostrar(DocenteDAO.getInstancia().ordenar("ap_m"), modelo); break;
                case 4: DocenteDAO.getInstancia().mostrar(DocenteDAO.getInstancia().ordenar("edad"), modelo); break;
                case 5: DocenteDAO.getInstancia().mostrar(DocenteDAO.getInstancia().ordenar("f_nacimiento"), modelo); break;
                case 6: DocenteDAO.getInstancia().mostrar(DocenteDAO.getInstancia().ordenar("sueldo"), modelo); break;
            
            }
         
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        }
        
            
    }//GEN-LAST:event_cboOrdenarActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        if(i!=-1){
            docenteSelec = new Docente();
            docenteSelec.setDni(modelo.getValueAt(i,0).toString());
            this.dispose();
        }else JOptionPane.showMessageDialog(null, "Seleccione un docente de la tabla");
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void txtBuscDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscDNIKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        String id = txtBuscDNI.getText();
        
        if(!Character.isDigit(c)){
             evt.consume();
         }
        if(id.length()==8)
            evt.consume();
    }//GEN-LAST:event_txtBuscDNIKeyTyped

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        try {
            String dni = txtDNI.getText().trim();
            double sueldo = Double.parseDouble(txtSueldo.getText());
            String nombre = txtNombre.getText().trim();
            String apellido_p = txtApellidoPat.getText().trim();
            String apellido_m = txtApellidoMat.getText().trim();
            String sexo="";

            if (rbtnM.isSelected()) {
                sexo = "MASCULINO";
            }else
                if (rbtnF.isSelected())sexo = "FEMENINO";

            int edad = (int) spnnrEdad.getValue();
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            String fechaNacimiento = formato.format(jdFechaNac.getDate());
            String telefono = txtTelefono.getText().trim();
            String password = dni;
            password = ENC.SHA256(password);
            Docente x = new Docente(sueldo, dni, password, nombre, apellido_p, apellido_m, sexo, edad, telefono, fechaNacimiento);
            if(UsuarioDAO.getInstancia().buscarUsuario(x.getDni())==null && ApoderadoDAO.getInstancia().buscar(x.getDni())==null){
                d.insertar(x);
                limpiar();
                d.mostrar(d.mostrarDocentes(), modelo);
                limpiar();
            }else{
                JOptionPane.showMessageDialog(null, "DNI ya existente en el registro", "Advertencia", 2);
            }
            
        } catch (SQLException | IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "Revisar Entrada de datos");
            System.out.println("Error: "+e.getMessage());
        } catch (NoSuchAlgorithmException ex) {
            System.out.println("Error: "+ex.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        String dni = txtDNI.getText();
        try {
            if(dni.equals("")){
                JOptionPane.showMessageDialog(null, "Ingrese DNI para consultas");
            }else{
                docenteBusc = DocenteDAO.getInstancia().buscarDocente(dni);
                if(docenteBusc!=null){

                    txtApellidoMat.setText(docenteBusc.getApellido_m());
                    txtApellidoPat.setText(docenteBusc.getApellido_p());
                    txtNombre.setText(docenteBusc.getNombre());
                    spnnrEdad.setValue(docenteBusc.getEdad());
                    txtTelefono.setText(docenteBusc.getTelefono());
                    txtSueldo.setText(String.format(Locale.US,"%.2f",docenteBusc.getSueldo()));
                    if(docenteBusc.getSexo().equalsIgnoreCase("MASCULINO"))
                        rbtnM.setSelected(true);
                    else 
                        rbtnF.setSelected(true);
                    java.util.Date fecha_nac = new SimpleDateFormat("yyyy-MM-dd").parse(docenteBusc.getFecha_nacimiento());
                    jdFechaNac.setDate(fecha_nac);
                    activar();
                }else JOptionPane.showMessageDialog(null, "No se econtró en el registro");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        } catch (ParseException ex) {
            Logger.getLogger(DialogDocentes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        try {
            String dni = txtDNI.getText().trim();
            double sueldo = Double.parseDouble(txtSueldo.getText());
            String nombre = txtNombre.getText().trim();
            String apellido_p = txtApellidoPat.getText().trim();
            String apellido_m = txtApellidoMat.getText().trim();
            String sexo="";

            if (rbtnM.isSelected()) {
                sexo = "MASCULINO";
            }else
                if (rbtnF.isSelected())sexo = "FEMENINO";

            int edad = (int) spnnrEdad.getValue();
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            String fechaNacimiento = formato.format(jdFechaNac.getDate());
            String telefono = txtTelefono.getText().trim();
            String password="";
            Docente x = new Docente(sueldo, dni, password, nombre, apellido_p, apellido_m, sexo, edad, telefono, fechaNacimiento);
            d.actualizar(x);
            d.mostrar(d.mostrarDocentes(), modelo);
            JOptionPane.showMessageDialog(null, "ACTUALIZADO");
            limpiar();
            desactivar();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        try {
            DocenteDAO.getInstancia().eliminar(docenteBusc.getDni());
            JOptionPane.showMessageDialog(null,"Docente eliminado");
            limpiar();
            desactivar();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Acción restringida: No se puede eliminar un docente que enseña en un curso donde hay\nalumnos matriculados", "Advertencia", 0);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        desactivar();
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtApellidoMatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoMatKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMatKeyTyped

    private void txtDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyTyped
    
        char c=evt.getKeyChar();
        String id = txtDNI.getText();
        
        if(!Character.isDigit(c)){
             evt.consume();
         }
        if(id.length()==8)
            evt.consume();
    }//GEN-LAST:event_txtDNIKeyTyped

    private void txtSueldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSueldoKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        int punto=txtSueldo.getText().indexOf(".")+1;
        if(punto==0){
            if(!Character.isDigit(c) && c!='.')
               evt.consume();
        }
        else{
              if(!Character.isDigit(c))
                 evt.consume();
            }
    }//GEN-LAST:event_txtSueldoKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char c=evt.getKeyChar();
        String id = txtTelefono.getText();
        
        if(!Character.isDigit(c)){
             evt.consume();
         }
        if(id.length()==9)
            evt.consume();
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSueldoActionPerformed

    private void btnReestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReestablecerActionPerformed
        try{
            String dni = txtDNI.getText().trim();
            String passw = dni;
            passw = ENC.SHA256(passw);
            DocenteDAO.getInstancia().actualizarPass(dni, passw);
            JOptionPane.showMessageDialog(null, "Se ha restablecido la contraseña exitosamente.\nLa contraseña corresponde al número de DNI", "Éxito", 1);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "ERROR: "+ e.getMessage(), "error 4040", 0);
        } catch (NoSuchAlgorithmException ex) {
            System.out.println("ERROR: "+ex.getMessage());
        }
    }//GEN-LAST:event_btnReestablecerActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DialogDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DialogDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DialogDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DialogDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DialogDocentes dialog = new DialogDocentes(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarEnTabla;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnReestablecer;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboOrdenar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser jdFechaNac;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JRadioButton rbtnF;
    private javax.swing.JRadioButton rbtnM;
    private javax.swing.JSpinner spnnrEdad;
    private javax.swing.JTextField txtApellidoMat;
    private javax.swing.JTextField txtApellidoPat;
    private javax.swing.JTextField txtBuscDNI;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSueldo;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
