/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import datos.CursoDAO;
import datos.MatriculaDAO;
import entidad.Curso;
import entidad.Matricula;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author hiro
 */
public class DialogAlumnoGraficoNota extends javax.swing.JDialog {
    Curso c = null;
    Matricula m=null;
    /**
     * Creates new form DialogAlumnoGraficoNota
     * @param c
     * @param m
     */
    public DialogAlumnoGraficoNota(Curso c, Matricula m) {
        super(FrmInicioAlumno.getInstancia(), true);
        initComponents();

        setLocationRelativeTo(null);
        
        this.c=c;
        this.m=m;
        try{
            graficar(c);
        }catch(SQLException e){
            System.out.println("Error. No hay curso seleccionado");
        }
        
    }
    
    
    
    public void graficar(Curso curso) throws SQLException{
        lblCurso.setText("CURSO: "+c.getNombre());
        ArrayList<Double> promedioBimestral= MatriculaDAO.getInstancia().promedioBimestreCurso(m, curso);
        DefaultCategoryDataset datos = new DefaultCategoryDataset();
        for (int i = 0;i<=3;i++){
            datos.setValue(promedioBimestral.get(i), curso.getNombre(), "Bimestre"+(i+1));
        }
        JFreeChart grafico_barras = ChartFactory.createBarChart3D(
            "Promedios Bimestrales",  //nombre del grafico
            "Año Académico",  //nombre de las barras o columnas
            "Calificación",      //nombre de la numeracion
            datos,  //datos del grafico
            PlotOrientation.VERTICAL,//orientacion
            true,    //legenda de barras individuales por color
            true, //herramientas
            false//url del grafico
        );
        CategoryPlot plot =grafico_barras.getCategoryPlot();
        NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
        rangeAxis.setRange(0, 20); 
        ChartPanel panel = new ChartPanel(grafico_barras);
        panel.setMouseWheelEnabled(false);
        panel.setDomainZoomable(false);
        panel.setRangeZoomable(false);
        panel.setPreferredSize(new Dimension(970, 470));
        panelGrafico.setLayout(new BorderLayout());
        panelGrafico.add(panel,BorderLayout.NORTH);
        pack();
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBack = new javax.swing.JPanel();
        lblCurso = new javax.swing.JLabel();
        panelGrafico = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBack.setBackground(new java.awt.Color(26, 2, 58));
        pnlBack.setForeground(new java.awt.Color(255, 255, 255));
        pnlBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCurso.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        lblCurso.setForeground(new java.awt.Color(255, 255, 255));
        lblCurso.setText("CURSO");
        pnlBack.add(lblCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 35, -1, -1));

        javax.swing.GroupLayout panelGraficoLayout = new javax.swing.GroupLayout(panelGrafico);
        panelGrafico.setLayout(panelGraficoLayout);
        panelGraficoLayout.setHorizontalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        panelGraficoLayout.setVerticalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        pnlBack.add(panelGrafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 1050, 470));

        getContentPane().add(pnlBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1100, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DialogAlumnoGraficoNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DialogAlumnoGraficoNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DialogAlumnoGraficoNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DialogAlumnoGraficoNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DialogAlumnoGraficoNota dialog = new DialogAlumnoGraficoNota(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCurso;
    private javax.swing.JPanel panelGrafico;
    private javax.swing.JPanel pnlBack;
    // End of variables declaration//GEN-END:variables
}
