/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;
import datos.CursoDAO;
import datos.MatriculaDAO;
import entidad.*;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Piero
 */
public class DialogMatriculaFromAlumno extends javax.swing.JDialog {

    Alumno a = null;
    Matricula m = null;
    DefaultTableModel modelo = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    public DialogMatriculaFromAlumno() {
        super(FrmInicioSecretaria.getInstancia(),true);
        initComponents();
        setLocationRelativeTo(null);
    }

    public void setA(Alumno alumno) {
        a = alumno;
        iniciar();
    }

    public void iniciar(){
        try {
            this.m = MatriculaDAO.getInstancia().buscarMatriculaPorDniAlumno(a.getDni());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERROR: "+ex.getMessage(), "", 0);
        }
        datosMatricula(m);
        datosAlumno(m.getAlumno());
        datosApoderado(m.getAlumno().getApoderado());
        datosGrado(m.getGrado());
        cursosMatriculados(m.getGrado());
        try {
            CursoDAO.getInstancia().mostrar(CursoDAO.getInstancia().mostrarPorGrado(m.getGrado().getIdGrado()), modelo);
        } catch (SQLException ex) {
            Logger.getLogger(DialogMatriculaFromAlumno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void datosAlumno(Alumno a){
        txtDni.setText(a.getDni());
        txtNombre.setText(a.getNombre());
        txtTelefono.setText(a.getTelefono());
        txtApellidoP.setText(a.getApellido_p());
        txtApellidoM.setText(a.getApellido_m());
        txtEdad.setText(String.valueOf(a.getEdad()));
        txtSexo.setText(a.getSexo());
        txtFechaDeNacimiento.setText(a.getFecha_nacimiento());
        txaObservacion.setText(a.getObservacion());
    }
    
    public void datosApoderado(Apoderado ap){
        txtApoderadoDni.setText(a.getApoderado().getDni());
        txtNombreApoderado.setText(a.getApoderado().getNombre());
        txtApoderadoAP.setText(a.getApoderado().getAp_p());
        
        txtApoderadoTel.setText(a.getApoderado().getTelefono());
    }
    public void datosGrado(Grado g){
        txtNumGrado.setText(String.valueOf(g.getNumGrado()));
        txtSeccion.setText(g.getSeccion());
    }
    
    public void datosMatricula(Matricula m){
        txtIdMatricula.setText(m.getId());
        txtFechaMatricula.setText(m.getFecha());
        Secretaria s = m.getSecretaria();
        txtNombreSecretaria.setText(s.getNombre()+' '+s.getApellido_p()+' '+s.getApellido_m());
    }
    
    public void cursosMatriculados(Grado g){
        ArrayList<Curso> lc;
        try {
            lc = CursoDAO.getInstancia().mostrarPorGrado(g.getIdGrado());
            CursoDAO.getInstancia().mostrar(lc, modelo);
        } catch (SQLException ex) {
            Logger.getLogger(DialogMatriculaFromAlumno.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSide = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtEdad = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaObservacion = new javax.swing.JTextArea();
        txtDni = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtFechaDeNacimiento = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        txtSeccion = new javax.swing.JTextField();
        txtNumGrado = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        txtIdMatricula = new javax.swing.JTextField();
        txtFechaMatricula = new javax.swing.JTextField();
        txtNombreSecretaria = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSalir4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txtApoderadoTel = new javax.swing.JTextField();
        txtApoderadoDni = new javax.swing.JTextField();
        txtNombreApoderado = new javax.swing.JTextField();
        txtApoderadoAP = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlSide1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSide.setBackground(new java.awt.Color(230, 233, 242));
        pnlSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        jLabel3.setText("FICHA DE MATRÍCULA - AÑO 2022");
        pnlSide.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 790, 50));

        jPanel4.setBackground(new java.awt.Color(24, 2, 56));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEdad.setEditable(false);
        txtEdad.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtEdad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEdad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtEdad.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        jPanel4.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 229, 30));

        txtApellidoP.setEditable(false);
        txtApellidoP.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtApellidoP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApellidoP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtApellidoP.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtApellidoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPActionPerformed(evt);
            }
        });
        jPanel4.add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 230, 30));

        txtApellidoM.setEditable(false);
        txtApellidoM.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtApellidoM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApellidoM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtApellidoM.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtApellidoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMActionPerformed(evt);
            }
        });
        jPanel4.add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 230, 30));

        txtTelefono.setEditable(false);
        txtTelefono.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtTelefono.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        jPanel4.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 230, 30));

        txaObservacion.setEditable(false);
        txaObservacion.setColumns(20);
        txaObservacion.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txaObservacion.setRows(5);
        txaObservacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txaObservacion.setSelectionColor(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(txaObservacion);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 500, 120));

        txtDni.setEditable(false);
        txtDni.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtDni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDni.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDni.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });
        jPanel4.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 230, 30));

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNombre.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel4.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 229, 30));

        txtFechaDeNacimiento.setEditable(false);
        txtFechaDeNacimiento.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtFechaDeNacimiento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechaDeNacimiento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtFechaDeNacimiento.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtFechaDeNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaDeNacimientoActionPerformed(evt);
            }
        });
        jPanel4.add(txtFechaDeNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 229, 30));

        txtSexo.setEditable(false);
        txtSexo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtSexo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSexo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtSexo.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexoActionPerformed(evt);
            }
        });
        jPanel4.add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 230, 30));

        jLabel15.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("DNI");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel16.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("APELLIDO PATERNO");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel17.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("EDAD");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        jLabel18.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("SEXO");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel19.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("TELEFONO");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel20.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("APELLIDO MATERNO");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        jLabel21.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("OBSERVACION");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLabel22.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("NOMBRE");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel23.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("FECHA DE NACIMIENTO");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        pnlSide.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 600, 530));

        jLabel10.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(25, 0, 58));
        jLabel10.setText("CURSOS MATRICULADOS");
        pnlSide.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 480, -1, -1));

        jLabel11.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(25, 0, 58));
        jLabel11.setText("INFORMACION PERSONAL DEL ALUMNO");
        pnlSide.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(25, 0, 58));
        jLabel12.setText("GRADO ACADÉMICO");
        pnlSide.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, -1, -1));

        jLabel13.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(25, 0, 58));
        jLabel13.setText("DATOS DE APODERADO");
        pnlSide.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 140, -1, -1));

        jPanel8.setBackground(new java.awt.Color(24, 2, 56));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSeccion.setEditable(false);
        txtSeccion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSeccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSeccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtSeccion.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeccionActionPerformed(evt);
            }
        });
        jPanel8.add(txtSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 210, 40));

        txtNumGrado.setEditable(false);
        txtNumGrado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtNumGrado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumGrado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNumGrado.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtNumGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumGradoActionPerformed(evt);
            }
        });
        jPanel8.add(txtNumGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 210, 40));

        jLabel28.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("NOMBRE DE LA SECRETARIA");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        jLabel29.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("NOMBRE DE LA SECRETARIA");
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        jLabel30.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("SECCIÓN:");
        jPanel8.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel31.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("GRADO");
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        pnlSide.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, 290, 180));

        jPanel7.setBackground(new java.awt.Color(24, 2, 56));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdMatricula.setEditable(false);
        txtIdMatricula.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtIdMatricula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdMatricula.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtIdMatricula.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtIdMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMatriculaActionPerformed(evt);
            }
        });
        txtIdMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdMatriculaKeyTyped(evt);
            }
        });
        jPanel7.add(txtIdMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 170, 40));

        txtFechaMatricula.setEditable(false);
        txtFechaMatricula.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtFechaMatricula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechaMatricula.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtFechaMatricula.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtFechaMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaMatriculaActionPerformed(evt);
            }
        });
        txtFechaMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaMatriculaKeyTyped(evt);
            }
        });
        jPanel7.add(txtFechaMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 160, 40));

        txtNombreSecretaria.setEditable(false);
        txtNombreSecretaria.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtNombreSecretaria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreSecretaria.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNombreSecretaria.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtNombreSecretaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreSecretariaActionPerformed(evt);
            }
        });
        txtNombreSecretaria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreSecretariaKeyTyped(evt);
            }
        });
        jPanel7.add(txtNombreSecretaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 370, 40));

        jLabel24.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("NOMBRE DE LA SECRETARIA");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        jLabel25.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("ID MATRICULA");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel26.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("FECHA");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        pnlSide.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 810, 100));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-matricula.png"))); // NOI18N
        pnlSide.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, -1, -1));

        btnSalir4.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        btnSalir4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-salir.png"))); // NOI18N
        btnSalir4.setText("SALIR");
        btnSalir4.setBorder(null);
        btnSalir4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir4ActionPerformed(evt);
            }
        });
        pnlSide.add(btnSalir4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 820, 180, 40));

        jPanel6.setBackground(new java.awt.Color(24, 2, 56));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtApoderadoTel.setEditable(false);
        txtApoderadoTel.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtApoderadoTel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApoderadoTel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtApoderadoTel.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtApoderadoTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApoderadoTelActionPerformed(evt);
            }
        });
        jPanel6.add(txtApoderadoTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 210, 30));

        txtApoderadoDni.setEditable(false);
        txtApoderadoDni.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtApoderadoDni.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApoderadoDni.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtApoderadoDni.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtApoderadoDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApoderadoDniActionPerformed(evt);
            }
        });
        jPanel6.add(txtApoderadoDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 210, 30));

        txtNombreApoderado.setEditable(false);
        txtNombreApoderado.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtNombreApoderado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreApoderado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNombreApoderado.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtNombreApoderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreApoderadoActionPerformed(evt);
            }
        });
        jPanel6.add(txtNombreApoderado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 210, 30));

        txtApoderadoAP.setEditable(false);
        txtApoderadoAP.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtApoderadoAP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApoderadoAP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtApoderadoAP.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtApoderadoAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApoderadoAPActionPerformed(evt);
            }
        });
        jPanel6.add(txtApoderadoAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 210, 30));

        jLabel32.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("DNI");
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 30, -1));

        jLabel33.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("NOMBRE");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel34.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("TELEFONO");
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel36.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("APELLIDOS");
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        pnlSide.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 180, 290, 290));

        jLabel14.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(25, 0, 58));
        jLabel14.setText("DATOS DE MATRÍCULA");
        pnlSide.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));
        pnlSide.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 210, -1, -1));

        jPanel2.setBackground(new java.awt.Color(194, 36, 45));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        jTable1.setModel(modelo
        );
        jTable1.setEnabled(false);
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(22);
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 720, 260));

        pnlSide.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, 790, 300));

        pnlSide1.setBackground(new java.awt.Color(26, 2, 58));
        pnlSide.add(pnlSide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 900));

        getContentPane().add(pnlSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1530, 880));

        setSize(new java.awt.Dimension(1483, 927));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void txtApellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPActionPerformed

    private void txtApellidoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtApoderadoTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApoderadoTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApoderadoTelActionPerformed

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtFechaDeNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaDeNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaDeNacimientoActionPerformed

    private void txtSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexoActionPerformed

    private void txtIdMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMatriculaActionPerformed

    private void txtIdMatriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdMatriculaKeyTyped
        // TODO add your handling code here:
        if (txtIdMatricula.getText().length()==10){
            evt.consume();
        }
    }//GEN-LAST:event_txtIdMatriculaKeyTyped

    private void txtSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeccionActionPerformed

    private void txtNumGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumGradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumGradoActionPerformed

    private void btnSalir4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir4ActionPerformed
        // TODO add your handling code here:
        dispose();
      
    }//GEN-LAST:event_btnSalir4ActionPerformed

    private void txtFechaMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaMatriculaActionPerformed

    private void txtFechaMatriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaMatriculaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaMatriculaKeyTyped

    private void txtApoderadoDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApoderadoDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApoderadoDniActionPerformed

    private void txtNombreApoderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreApoderadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreApoderadoActionPerformed

    private void txtApoderadoAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApoderadoAPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApoderadoAPActionPerformed

    private void txtNombreSecretariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreSecretariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreSecretariaActionPerformed

    private void txtNombreSecretariaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreSecretariaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreSecretariaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogMatriculaFromAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogMatriculaFromAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogMatriculaFromAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogMatriculaFromAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogMatriculaFromAlumno dialog = new DialogMatriculaFromAlumno();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlSide;
    private javax.swing.JPanel pnlSide1;
    private javax.swing.JTextArea txaObservacion;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtApoderadoAP;
    private javax.swing.JTextField txtApoderadoDni;
    private javax.swing.JTextField txtApoderadoTel;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFechaDeNacimiento;
    private javax.swing.JTextField txtFechaMatricula;
    private javax.swing.JTextField txtIdMatricula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreApoderado;
    private javax.swing.JTextField txtNombreSecretaria;
    private javax.swing.JTextField txtNumGrado;
    private javax.swing.JTextField txtSeccion;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
