/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;


import datos.AlumnoDAO;
import datos.BimestreDAO;
import datos.CursoDAO;
import datos.MatriculaDAO;
import entidad.Alumno;
import entidad.Bimestre;
import entidad.Curso;
import entidad.Matricula;
import java.awt.Color;
import java.sql.*;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Johann
 */
public class DialogAlumnoNotas extends javax.swing.JDialog {

    Alumno a = null;
    Matricula m = null;
    ArrayList <Curso> listaCursos = new ArrayList<>();
    DefaultTableModel modelo = new DefaultTableModel();
    public DialogAlumnoNotas() {
        super(FrmInicioAlumno.getInstancia(), true);
        initComponents();
        setLocationRelativeTo(null);
        
        
    }
    public void setAlumno(Alumno alumno){
        a = alumno;
        llenarDatos();
        try {
            listaCursos = CursoDAO.getInstancia().mostrarPorGrado(m.getGrado().getIdGrado());
            llenarCursos();
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR: "+e.getMessage(),"",0);
        }
        
    }
    private void llenarCursos(){
        for(int i=0; i<listaCursos.size();i++){
            cboCurso.addItem(listaCursos.get(i).getNombre());
        }
    }
    private void llenarDatos(){
        lblAlumno.setText(a.getApellido_p()+" "+a.getApellido_m()+", "+a.getNombre());
        try {
            m = MatriculaDAO.getInstancia().buscarMatriculaPorDniAlumno(a.getDni());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR: "+e.getMessage(),"",0);
        }
        lblGrado.setText(String.valueOf(m.getGrado().getNumGrado()));
        lblSeccion.setText(m.getGrado().getSeccion());
    }
    
    private void limpiarDatos(){
        btngSemana1.clearSelection();
        btngSemana2.clearSelection();
        btngSemana3.clearSelection();
        btngSemana4.clearSelection();
        btngSemana5.clearSelection();
        btngSemana6.clearSelection();
        btngSemana7.clearSelection();
        btngSemana8.clearSelection();
        txtN1.setText("");
        txtN2.setText("");
        txtN3.setText("");
        txtN4.setText("");
        txtN5.setText("");
        txtN6.setText("");
        txtN7.setText("");
        txtN8.setText("");
        txtPromedio.setText("");
        cboBimestre.setSelectedIndex(0);
        cboCurso.setSelectedIndex(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngSemana1 = new javax.swing.ButtonGroup();
        btngSemana2 = new javax.swing.ButtonGroup();
        btngSemana3 = new javax.swing.ButtonGroup();
        btngSemana4 = new javax.swing.ButtonGroup();
        btngSemana5 = new javax.swing.ButtonGroup();
        btngSemana6 = new javax.swing.ButtonGroup();
        btngSemana7 = new javax.swing.ButtonGroup();
        btngSemana8 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cboCurso = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblAlumno = new javax.swing.JLabel();
        lblGrado = new javax.swing.JLabel();
        lblSeccion = new javax.swing.JLabel();
        cboBimestre = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        pnlRed = new javax.swing.JPanel();
        lblNota = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        rbF1 = new javax.swing.JRadioButton();
        rbA1 = new javax.swing.JRadioButton();
        rbT1 = new javax.swing.JRadioButton();
        rbA2 = new javax.swing.JRadioButton();
        rbA3 = new javax.swing.JRadioButton();
        rbA4 = new javax.swing.JRadioButton();
        rbA5 = new javax.swing.JRadioButton();
        rbA6 = new javax.swing.JRadioButton();
        rbA7 = new javax.swing.JRadioButton();
        rbA8 = new javax.swing.JRadioButton();
        rbT2 = new javax.swing.JRadioButton();
        rbT3 = new javax.swing.JRadioButton();
        rbT4 = new javax.swing.JRadioButton();
        rbT5 = new javax.swing.JRadioButton();
        rbT6 = new javax.swing.JRadioButton();
        rbT7 = new javax.swing.JRadioButton();
        rbT8 = new javax.swing.JRadioButton();
        rbF2 = new javax.swing.JRadioButton();
        rbF3 = new javax.swing.JRadioButton();
        rbF4 = new javax.swing.JRadioButton();
        rbF5 = new javax.swing.JRadioButton();
        rbF6 = new javax.swing.JRadioButton();
        rbF7 = new javax.swing.JRadioButton();
        rbF8 = new javax.swing.JRadioButton();
        rbFJ7 = new javax.swing.JRadioButton();
        rbFJ8 = new javax.swing.JRadioButton();
        rbFJ6 = new javax.swing.JRadioButton();
        rbFJ5 = new javax.swing.JRadioButton();
        rbFJ4 = new javax.swing.JRadioButton();
        rbFJ3 = new javax.swing.JRadioButton();
        rbFJ2 = new javax.swing.JRadioButton();
        rbFJ1 = new javax.swing.JRadioButton();
        lblNota1 = new javax.swing.JLabel();
        lblfecha1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtN1 = new javax.swing.JTextField();
        txtN2 = new javax.swing.JTextField();
        txtN3 = new javax.swing.JTextField();
        txtN4 = new javax.swing.JTextField();
        txtN5 = new javax.swing.JTextField();
        txtN6 = new javax.swing.JTextField();
        txtN7 = new javax.swing.JTextField();
        txtN8 = new javax.swing.JTextField();
        lblfecha2 = new javax.swing.JLabel();
        lblfecha3 = new javax.swing.JLabel();
        lblfecha4 = new javax.swing.JLabel();
        lblfecha5 = new javax.swing.JLabel();
        lblfecha6 = new javax.swing.JLabel();
        lblfecha7 = new javax.swing.JLabel();
        lblfecha8 = new javax.swing.JLabel();
        lblfecha9 = new javax.swing.JLabel();
        txtPromedio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pnlBack = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 950));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(26, 2, 58));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 950));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 54)); // NOI18N
        jLabel2.setText("REPORTE DE NOTAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 510, 50));

        cboCurso.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        cboCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECCIONAR>" }));
        cboCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCursoActionPerformed(evt);
            }
        });
        getContentPane().add(cboCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 340, 40));

        jLabel10.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(25, 0, 58));
        jLabel10.setText("SECCIÓN");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(25, 0, 58));
        jLabel11.setText("BIMESTRE");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(25, 0, 58));
        jLabel12.setText("ALUMNO");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jLabel13.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(25, 0, 58));
        jLabel13.setText("GRADO");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));

        lblAlumno.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        getContentPane().add(lblAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 400, 30));

        lblGrado.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        getContentPane().add(lblGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 80, 30));

        lblSeccion.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        getContentPane().add(lblSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 150, 110, 30));

        cboBimestre.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        cboBimestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECCIONAR>", "I", "II", "III", "IV" }));
        cboBimestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboBimestreActionPerformed(evt);
            }
        });
        getContentPane().add(cboBimestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 170, 40));

        jLabel14.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(25, 0, 58));
        jLabel14.setText("CURSO");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        pnlRed.setBackground(new java.awt.Color(194, 36, 45));
        pnlRed.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N
        pnlRed.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNota.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblNota.setForeground(new java.awt.Color(255, 255, 255));
        lblNota.setText("Nota");
        pnlRed.add(lblNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btngSemana1.add(rbF1);
        rbF1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbF1.setText("Falta");
        rbF1.setEnabled(false);
        rbF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbF1ActionPerformed(evt);
            }
        });
        jPanel4.add(rbF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, 30));

        btngSemana1.add(rbA1);
        rbA1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbA1.setText("Presente");
        rbA1.setEnabled(false);
        jPanel4.add(rbA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        btngSemana1.add(rbT1);
        rbT1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbT1.setText("Tardanza");
        rbT1.setEnabled(false);
        rbT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbT1ActionPerformed(evt);
            }
        });
        jPanel4.add(rbT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 30));

        btngSemana2.add(rbA2);
        rbA2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbA2.setText("Presente");
        rbA2.setEnabled(false);
        jPanel4.add(rbA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 30));

        btngSemana3.add(rbA3);
        rbA3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbA3.setText("Presente");
        rbA3.setEnabled(false);
        jPanel4.add(rbA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 30));

        btngSemana4.add(rbA4);
        rbA4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbA4.setText("Presente");
        rbA4.setEnabled(false);
        jPanel4.add(rbA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));

        btngSemana5.add(rbA5);
        rbA5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbA5.setText("Presente");
        rbA5.setEnabled(false);
        jPanel4.add(rbA5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 30));

        btngSemana6.add(rbA6);
        rbA6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbA6.setText("Presente");
        rbA6.setEnabled(false);
        jPanel4.add(rbA6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 30));

        btngSemana7.add(rbA7);
        rbA7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbA7.setText("Presente");
        rbA7.setEnabled(false);
        jPanel4.add(rbA7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 30));

        btngSemana8.add(rbA8);
        rbA8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbA8.setText("Presente");
        rbA8.setEnabled(false);
        jPanel4.add(rbA8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 30));

        btngSemana2.add(rbT2);
        rbT2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbT2.setText("Tardanza");
        rbT2.setEnabled(false);
        jPanel4.add(rbT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, 30));

        btngSemana3.add(rbT3);
        rbT3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbT3.setText("Tardanza");
        rbT3.setEnabled(false);
        jPanel4.add(rbT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, 30));

        btngSemana4.add(rbT4);
        rbT4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbT4.setText("Tardanza");
        rbT4.setEnabled(false);
        jPanel4.add(rbT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, 30));

        btngSemana5.add(rbT5);
        rbT5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbT5.setText("Tardanza");
        rbT5.setEnabled(false);
        jPanel4.add(rbT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, 30));

        btngSemana6.add(rbT6);
        rbT6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbT6.setText("Tardanza");
        rbT6.setEnabled(false);
        jPanel4.add(rbT6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, 30));

        btngSemana7.add(rbT7);
        rbT7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbT7.setText("Tardanza");
        rbT7.setEnabled(false);
        jPanel4.add(rbT7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, 30));

        btngSemana8.add(rbT8);
        rbT8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbT8.setText("Tardanza");
        rbT8.setEnabled(false);
        jPanel4.add(rbT8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, 30));

        btngSemana2.add(rbF2);
        rbF2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbF2.setText("Falta");
        rbF2.setEnabled(false);
        rbF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbF2ActionPerformed(evt);
            }
        });
        jPanel4.add(rbF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, 30));

        btngSemana3.add(rbF3);
        rbF3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbF3.setText("Falta");
        rbF3.setEnabled(false);
        rbF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbF3ActionPerformed(evt);
            }
        });
        jPanel4.add(rbF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, 30));

        btngSemana4.add(rbF4);
        rbF4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbF4.setText("Falta");
        rbF4.setEnabled(false);
        rbF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbF4ActionPerformed(evt);
            }
        });
        jPanel4.add(rbF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, 30));

        btngSemana5.add(rbF5);
        rbF5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbF5.setText("Falta");
        rbF5.setEnabled(false);
        rbF5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbF5ActionPerformed(evt);
            }
        });
        jPanel4.add(rbF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, 30));

        btngSemana6.add(rbF6);
        rbF6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbF6.setText("Falta");
        rbF6.setEnabled(false);
        rbF6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbF6ActionPerformed(evt);
            }
        });
        jPanel4.add(rbF6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, 30));

        btngSemana7.add(rbF7);
        rbF7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbF7.setText("Falta");
        rbF7.setEnabled(false);
        rbF7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbF7ActionPerformed(evt);
            }
        });
        jPanel4.add(rbF7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, 30));

        btngSemana8.add(rbF8);
        rbF8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbF8.setText("Falta");
        rbF8.setEnabled(false);
        rbF8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbF8ActionPerformed(evt);
            }
        });
        jPanel4.add(rbF8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, 30));

        btngSemana7.add(rbFJ7);
        rbFJ7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbFJ7.setText("Falta Justificada");
        rbFJ7.setEnabled(false);
        rbFJ7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFJ7ActionPerformed(evt);
            }
        });
        jPanel4.add(rbFJ7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, 30));

        btngSemana8.add(rbFJ8);
        rbFJ8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbFJ8.setText("Falta Justificada");
        rbFJ8.setEnabled(false);
        rbFJ8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFJ8ActionPerformed(evt);
            }
        });
        jPanel4.add(rbFJ8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, 30));

        btngSemana6.add(rbFJ6);
        rbFJ6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbFJ6.setText("Falta Justificada");
        rbFJ6.setEnabled(false);
        rbFJ6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFJ6ActionPerformed(evt);
            }
        });
        jPanel4.add(rbFJ6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, 30));

        btngSemana5.add(rbFJ5);
        rbFJ5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbFJ5.setText("Falta Justificada");
        rbFJ5.setEnabled(false);
        rbFJ5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFJ5ActionPerformed(evt);
            }
        });
        jPanel4.add(rbFJ5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, 30));

        btngSemana4.add(rbFJ4);
        rbFJ4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbFJ4.setText("Falta Justificada");
        rbFJ4.setEnabled(false);
        rbFJ4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFJ4ActionPerformed(evt);
            }
        });
        jPanel4.add(rbFJ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, 30));

        btngSemana3.add(rbFJ3);
        rbFJ3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbFJ3.setText("Falta Justificada");
        rbFJ3.setEnabled(false);
        rbFJ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFJ3ActionPerformed(evt);
            }
        });
        jPanel4.add(rbFJ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, 30));

        btngSemana2.add(rbFJ2);
        rbFJ2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbFJ2.setText("Falta Justificada");
        rbFJ2.setEnabled(false);
        rbFJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFJ2ActionPerformed(evt);
            }
        });
        jPanel4.add(rbFJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, 30));

        btngSemana1.add(rbFJ1);
        rbFJ1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbFJ1.setText("Falta Justificada");
        rbFJ1.setEnabled(false);
        rbFJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFJ1ActionPerformed(evt);
            }
        });
        jPanel4.add(rbFJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, 30));

        pnlRed.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 460, 350));

        lblNota1.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblNota1.setForeground(new java.awt.Color(255, 255, 255));
        lblNota1.setText("Asistencia");
        pnlRed.add(lblNota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        lblfecha1.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblfecha1.setForeground(new java.awt.Color(255, 255, 255));
        lblfecha1.setText("Semana 1");
        pnlRed.add(lblfecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, 30));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtN1.setEditable(false);
        jPanel5.add(txtN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 30));

        txtN2.setEditable(false);
        jPanel5.add(txtN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 30));

        txtN3.setEditable(false);
        jPanel5.add(txtN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 50, 30));

        txtN4.setEditable(false);
        jPanel5.add(txtN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 50, 30));

        txtN5.setEditable(false);
        jPanel5.add(txtN5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 50, 30));

        txtN6.setEditable(false);
        jPanel5.add(txtN6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 50, 30));

        txtN7.setEditable(false);
        jPanel5.add(txtN7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 50, 30));

        txtN8.setEditable(false);
        jPanel5.add(txtN8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 50, 30));

        pnlRed.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, 70, 350));

        lblfecha2.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblfecha2.setForeground(new java.awt.Color(255, 255, 255));
        lblfecha2.setText("Semana 2");
        pnlRed.add(lblfecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, 30));

        lblfecha3.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblfecha3.setForeground(new java.awt.Color(255, 255, 255));
        lblfecha3.setText("Semana 3");
        pnlRed.add(lblfecha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, 30));

        lblfecha4.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblfecha4.setForeground(new java.awt.Color(255, 255, 255));
        lblfecha4.setText("Semana 4");
        pnlRed.add(lblfecha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, 30));

        lblfecha5.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblfecha5.setForeground(new java.awt.Color(255, 255, 255));
        lblfecha5.setText("Semana 5");
        pnlRed.add(lblfecha5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 30));

        lblfecha6.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblfecha6.setForeground(new java.awt.Color(255, 255, 255));
        lblfecha6.setText("Semana 6");
        pnlRed.add(lblfecha6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, 30));

        lblfecha7.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblfecha7.setForeground(new java.awt.Color(255, 255, 255));
        lblfecha7.setText("Semana 7");
        pnlRed.add(lblfecha7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, 30));

        lblfecha8.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblfecha8.setForeground(new java.awt.Color(255, 255, 255));
        lblfecha8.setText("Promedio Final");
        pnlRed.add(lblfecha8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, -1, 30));

        lblfecha9.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblfecha9.setForeground(new java.awt.Color(255, 255, 255));
        lblfecha9.setText("Semana 8");
        pnlRed.add(lblfecha9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, 30));

        txtPromedio.setEditable(false);
        pnlRed.add(txtPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 50, 30));

        getContentPane().add(pnlRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 1110, 490));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_calificaciones.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 70, 70));

        pnlBack.setBackground(new java.awt.Color(231, 235, 244));
        pnlBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pnlBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbF1ActionPerformed

    }//GEN-LAST:event_rbF1ActionPerformed

    private void rbF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbF2ActionPerformed

    private void rbF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbF3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbF3ActionPerformed

    private void rbF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbF4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbF4ActionPerformed

    private void rbF5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbF5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbF5ActionPerformed

    private void rbF6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbF6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbF6ActionPerformed

    private void rbF7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbF7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbF7ActionPerformed

    private void rbF8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbF8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbF8ActionPerformed

    private void rbFJ7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFJ7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFJ7ActionPerformed

    private void rbFJ8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFJ8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFJ8ActionPerformed

    private void rbFJ6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFJ6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFJ6ActionPerformed

    private void rbFJ5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFJ5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFJ5ActionPerformed

    private void rbFJ4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFJ4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFJ4ActionPerformed

    private void rbFJ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFJ3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFJ3ActionPerformed

    private void rbFJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFJ2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFJ2ActionPerformed

    private void rbFJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFJ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFJ1ActionPerformed

    private void rbT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbT1ActionPerformed
    private void llenarAsistencia_Notas(Bimestre bimestre){
            String asistenciaBinaria = bimestre.getAsistencia_binaria();
            
            if (asistenciaBinaria.substring(0,1).equals("3")) {
                rbA1.setSelected(true);
            } else if (asistenciaBinaria.substring(0,1).equals("2")) {
                rbT1.setSelected(true);
            } else if (asistenciaBinaria.substring(0,1).equals("1")) {
                rbFJ1.setSelected(true);
            } else if (asistenciaBinaria.substring(0,1).equals("0")) {
                rbF1.setSelected(true);
            }
            
            if (asistenciaBinaria.substring(1,2).equals("3")) {
                rbA2.setSelected(true);
            } else if (asistenciaBinaria.substring(1,2).equals("2")) {
                rbT2.setSelected(true);
            } else if (asistenciaBinaria.substring(1,2).equals("1")) {
                rbFJ2.setSelected(true);
            } else if (asistenciaBinaria.substring(1,2).equals("0")) {
                rbF2.setSelected(true);
            }
            if (asistenciaBinaria.substring(0,1).equals("3")) {
                rbA3.setSelected(true);
            } else if (asistenciaBinaria.substring(2,3).equals("2")) {
                rbT3.setSelected(true);
            } else if (asistenciaBinaria.substring(2,3).equals("1")) {
                rbFJ3.setSelected(true);
            } else if (asistenciaBinaria.substring(2,3).equals("0")) {
                rbF3.setSelected(true);
            }
           if (asistenciaBinaria.substring(3,4).equals("3")) {
                rbA4.setSelected(true);
            } else if (asistenciaBinaria.substring(3,4).equals("2")) {
                rbT4.setSelected(true);
            } else if (asistenciaBinaria.substring(3,4).equals("1")) {
                rbFJ4.setSelected(true);
            } else if (asistenciaBinaria.substring(3,4).equals("0")) {
                rbF4.setSelected(true);
            }
           if (asistenciaBinaria.substring(4,5).equals("3")) {
                rbA5.setSelected(true);
            } else if (asistenciaBinaria.substring(4,5).equals("2")) {
                rbT5.setSelected(true);
            } else if (asistenciaBinaria.substring(4,5).equals("1")) {
                rbFJ5.setSelected(true);
            } else if (asistenciaBinaria.substring(4,5).equals("0")) {
                rbF5.setSelected(true);
            }
            if (asistenciaBinaria.substring(5,6).equals("3")) {
                rbA6.setSelected(true);
            } else if (asistenciaBinaria.substring(5,6).equals("2")) {
                rbT6.setSelected(true);
            } else if (asistenciaBinaria.substring(5,6).equals("1")) {
                rbFJ6.setSelected(true);
            } else if (asistenciaBinaria.substring(5,6).equals("0")) {
                rbF6.setSelected(true);
            }
            if (asistenciaBinaria.substring(6,7).equals("3")) {
                rbA7.setSelected(true);
            } else if (asistenciaBinaria.substring(6,7).equals("2")) {
                rbT7.setSelected(true);
            } else if (asistenciaBinaria.substring(6,7).equals("1")) {
                rbFJ7.setSelected(true);
            } else if (asistenciaBinaria.substring(6,7).equals("0")) {
                rbF7.setSelected(true);
            }
            if (asistenciaBinaria.substring(7,8).equals("3")) {
                rbA8.setSelected(true);
            } else if (asistenciaBinaria.substring(7,8).equals("2")) {
                rbT8.setSelected(true);
            } else if (asistenciaBinaria.substring(7,8).equals("1")) {
                rbFJ8.setSelected(true);
            } else if (asistenciaBinaria.substring(7,8).equals("0")) {
                rbF8.setSelected(true);
            }
        
        txtN1.setText(String.format(Locale.US,"%.2f",bimestre.getN1()));
        txtN2.setText(String.format(Locale.US,"%.2f",bimestre.getN2()));
        txtN3.setText(String.format(Locale.US,"%.2f",bimestre.getN3()));
        txtN4.setText(String.format(Locale.US,"%.2f",bimestre.getN4()));
        txtN5.setText(String.format(Locale.US,"%.2f",bimestre.getN5()));
        txtN6.setText(String.format(Locale.US,"%.2f",bimestre.getN6()));
        txtN7.setText(String.format(Locale.US,"%.2f",bimestre.getN7()));
        txtN8.setText(String.format(Locale.US,"%.2f",bimestre.getN8()));
        
        txtPromedio.setText(String.format(Locale.US,"%.2f",bimestre.getPromedioBimestre()));
    }
    private void cboBimestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboBimestreActionPerformed
        // TODO add your handling code here:
        try {
            String nombreCursoSelect = cboCurso.getSelectedItem().toString();
            int pos=-1;
            for (int i = 0; i < listaCursos.size(); i++) {
                if(listaCursos.get(i).getNombre().equalsIgnoreCase(nombreCursoSelect))
                    pos = i;
            }
            if(pos!=-1){
                int cboSelect = cboBimestre.getSelectedIndex();
                if(cboSelect == 0)
                    limpiarDatos();
                else{ 
                    Bimestre bimestre = BimestreDAO.getInstancia().buscar(a.getDni(),listaCursos.get(pos).getIdCurso(), cboSelect);
                    if(bimestre!=null)
                        llenarAsistencia_Notas(bimestre);
                }
            }else {
                JOptionPane.showMessageDialog(null, "Seleccione un curso","REPORTE DE NOTAS",2);
                cboBimestre.setSelectedIndex(0);
            }
        }  catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR: "+e.getMessage(),"",0);
        }
    }//GEN-LAST:event_cboBimestreActionPerformed

    private void cboCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCursoActionPerformed
        // TODO add your handling code here:
        if(cboCurso.getSelectedIndex() == 0)
            limpiarDatos();
        else {
            try {
                String nombreCursoSelect = cboCurso.getSelectedItem().toString();
                int pos = -1;
                for (int i = 0; i < listaCursos.size(); i++) {
                    if (listaCursos.get(i).getNombre().equalsIgnoreCase(nombreCursoSelect)) {
                        pos = i;
                    }
                }
                if (pos != -1) {
                    int cboSelect = cboBimestre.getSelectedIndex();
                    
                        Bimestre bimestre = BimestreDAO.getInstancia().buscar(a.getDni(), listaCursos.get(pos).getIdCurso(), cboSelect);
                        if (bimestre != null) {
                            llenarAsistencia_Notas(bimestre);
                        }
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Seleccione un curso", "REPORTE DE NOTAS", 2);
                    cboBimestre.setSelectedIndex(0);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "ERROR: " + e.getMessage(), "", 0);
            }
        }
    }//GEN-LAST:event_cboCursoActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DialogAlumnoNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DialogAlumnoNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DialogAlumnoNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DialogAlumnoNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DialogAlumnoNotas dialog = new DialogAlumnoNotas(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngSemana1;
    private javax.swing.ButtonGroup btngSemana2;
    private javax.swing.ButtonGroup btngSemana3;
    private javax.swing.ButtonGroup btngSemana4;
    private javax.swing.ButtonGroup btngSemana5;
    private javax.swing.ButtonGroup btngSemana6;
    private javax.swing.ButtonGroup btngSemana7;
    private javax.swing.ButtonGroup btngSemana8;
    private javax.swing.JComboBox<String> cboBimestre;
    private javax.swing.JComboBox<String> cboCurso;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblAlumno;
    private javax.swing.JLabel lblGrado;
    private javax.swing.JLabel lblNota;
    private javax.swing.JLabel lblNota1;
    private javax.swing.JLabel lblSeccion;
    private javax.swing.JLabel lblfecha1;
    private javax.swing.JLabel lblfecha2;
    private javax.swing.JLabel lblfecha3;
    private javax.swing.JLabel lblfecha4;
    private javax.swing.JLabel lblfecha5;
    private javax.swing.JLabel lblfecha6;
    private javax.swing.JLabel lblfecha7;
    private javax.swing.JLabel lblfecha8;
    private javax.swing.JLabel lblfecha9;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JPanel pnlRed;
    private javax.swing.JRadioButton rbA1;
    private javax.swing.JRadioButton rbA2;
    private javax.swing.JRadioButton rbA3;
    private javax.swing.JRadioButton rbA4;
    private javax.swing.JRadioButton rbA5;
    private javax.swing.JRadioButton rbA6;
    private javax.swing.JRadioButton rbA7;
    private javax.swing.JRadioButton rbA8;
    private javax.swing.JRadioButton rbF1;
    private javax.swing.JRadioButton rbF2;
    private javax.swing.JRadioButton rbF3;
    private javax.swing.JRadioButton rbF4;
    private javax.swing.JRadioButton rbF5;
    private javax.swing.JRadioButton rbF6;
    private javax.swing.JRadioButton rbF7;
    private javax.swing.JRadioButton rbF8;
    private javax.swing.JRadioButton rbFJ1;
    private javax.swing.JRadioButton rbFJ2;
    private javax.swing.JRadioButton rbFJ3;
    private javax.swing.JRadioButton rbFJ4;
    private javax.swing.JRadioButton rbFJ5;
    private javax.swing.JRadioButton rbFJ6;
    private javax.swing.JRadioButton rbFJ7;
    private javax.swing.JRadioButton rbFJ8;
    private javax.swing.JRadioButton rbT1;
    private javax.swing.JRadioButton rbT2;
    private javax.swing.JRadioButton rbT3;
    private javax.swing.JRadioButton rbT4;
    private javax.swing.JRadioButton rbT5;
    private javax.swing.JRadioButton rbT6;
    private javax.swing.JRadioButton rbT7;
    private javax.swing.JRadioButton rbT8;
    private javax.swing.JTextField txtN1;
    private javax.swing.JTextField txtN2;
    private javax.swing.JTextField txtN3;
    private javax.swing.JTextField txtN4;
    private javax.swing.JTextField txtN5;
    private javax.swing.JTextField txtN6;
    private javax.swing.JTextField txtN7;
    private javax.swing.JTextField txtN8;
    private javax.swing.JTextField txtPromedio;
    // End of variables declaration//GEN-END:variables
}
