/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package presentacion;
import com.itextpdf.text.*;
import com.itextpdf.text.Font.FontFamily;
import com.itextpdf.text.pdf.*;
import datos.AlumnoDAO;
import datos.BimestreDAO;
import datos.CursoDAO;
import datos.GradoDAO;
import datos.MatriculaDAO;
import entidad.*;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author Piero
 */
public class DialogRegistroMatricula extends javax.swing.JDialog {

    Alumno a = null;
    Secretaria s = null;
    Grado g = null;
    Matricula m = null;
    MatriculaDAO MD = new MatriculaDAO();
    String matbus;
    Secretaria auxInicio;
    ArrayList <Curso> cursos = null;
    
    public DialogRegistroMatricula(Secretaria secre) {
        super(FrmInicioSecretaria.getInstancia(), true);
        initComponents();
        setLocationRelativeTo(null);
        s = secre;
        auxInicio=secre;
        txtNombreSecretaria.setText(s.nombreCompleto());
        txtDniSecretaria.setText(s.getDni());
        txaObservacion.setLineWrap(true);
    }

    public void datosAlumno(Alumno a){
        txtDni.setText(a.getDni());
        txtNombre.setText(a.getNombre());
        txtTelefono.setText(a.getTelefono());
        txtApellidoP.setText(a.getApellido_p());
        txtApellidoM.setText(a.getApellido_m());
        txtEdad.setText(String.valueOf(a.getEdad()));
        txtApoderadoDni.setText(a.getApoderado().getDni()); 
        txtApoderadoNom.setText(a.getApoderado().getNombre()+" "+a.getApoderado().getAp_p());
        txtSexo.setText(a.getSexo());
        txtFechaDeNacimiento.setText(a.getFecha_nacimiento());
        txaObservacion.setText(a.getObservacion());
    }
    
    public void datosGrado(Grado g){
        txtNumGrado.setText(String.valueOf(g.getNumGrado()));
        txtSeccion.setText(g.getSeccion());
    }
    
    public void datosSecretaria(Secretaria s){
        txtDniSecretaria.setText(s.getDni());
        txtNombreSecretaria.setText(s.nombreCompleto());
    }
    
    public void habilitar(){
        btnEliminar.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnConsultar.setEnabled(false);
        btnImprimirMatricula.setEnabled(true);
        txtIdMatricula.setEnabled(false);
        jDate.setEnabled(false);
        btnSeleccionAlumno.setEnabled(false);
        btnSeleccionGrado.setEnabled(false);
    }
     
    public void desHabilitar(){
        btnEliminar.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnConsultar.setEnabled(true);
        txtIdMatricula.setEnabled(true);
        jDate.setEnabled(true);
        btnSeleccionAlumno.setEnabled(true);
        btnSeleccionGrado.setEnabled(true);
    }     
    
    public void limpiarEntradas(){
        txtIdMatricula.setText("");
        txtDni.setText("");
        txtNombre.setText("");
        txtTelefono.setText("");
        txtApellidoP.setText("");
        txtApellidoM.setText("");
        txtApoderadoDni.setText("");
        txtSexo.setText("");
        txtEdad.setText("");
        txtFechaDeNacimiento.setText("");
        txaObservacion.setText("");
        txtNumGrado.setText("");
        txtSeccion.setText("");
        jDate.setCalendar(null);
        g=null;
        a=null;
        txtDni.requestFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtDniSecretaria = new javax.swing.JTextField();
        txtNombreSecretaria = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtEdad = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaObservacion = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        txtApoderadoDni = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txtApoderadoNom = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtFechaDeNacimiento = new javax.swing.JTextField();
        btnSeleccionAlumno = new javax.swing.JButton();
        txtSexo = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        txtSeccion = new javax.swing.JTextField();
        txtNumGrado = new javax.swing.JTextField();
        btnSeleccionGrado = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        txtIdMatricula = new javax.swing.JTextField();
        jDate = new com.toedter.calendar.JDateChooser();
        jLabel30 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btnImprimirMatricula = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnSalir4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1004, 840));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(26, 2, 58));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_log.png"))); // NOI18N
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 120, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 920));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-matricula.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 54)); // NOI18N
        jLabel3.setText("MATRICULA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 330, 50));

        jPanel3.setBackground(new java.awt.Color(26, 2, 58));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDniSecretaria.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtDniSecretaria.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDniSecretaria.setEnabled(false);
        txtDniSecretaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniSecretariaActionPerformed(evt);
            }
        });
        jPanel3.add(txtDniSecretaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, 30));

        txtNombreSecretaria.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNombreSecretaria.setEnabled(false);
        txtNombreSecretaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreSecretariaActionPerformed(evt);
            }
        });
        jPanel3.add(txtNombreSecretaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 190, 30));

        jLabel27.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("NOMBRE");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel29.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("DNI");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 390, 70));

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save_37110.png"))); // NOI18N
        btnGuardar.setText("REGISTRAR");
        btnGuardar.setBorder(null);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardar.setMinimumSize(new java.awt.Dimension(200, 200));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 180, 80));

        btnConsultar.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultar.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono-Consulta.png"))); // NOI18N
        btnConsultar.setText("BUSCAR");
        btnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConsultar.setMinimumSize(new java.awt.Dimension(200, 200));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 310, 180, 80));

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-Delete.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminar.setEnabled(false);
        btnEliminar.setMinimumSize(new java.awt.Dimension(200, 200));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 180, 80));

        jPanel1.setBackground(new java.awt.Color(231, 235, 244));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 0, 58));
        jLabel1.setText("Grado académico");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        jPanel4.setBackground(new java.awt.Color(26, 2, 58));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEdad.setEditable(false);
        txtEdad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        jPanel4.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 229, 30));

        txtApellidoP.setEditable(false);
        txtApellidoP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtApellidoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPActionPerformed(evt);
            }
        });
        jPanel4.add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 230, 30));

        txtApellidoM.setEditable(false);
        txtApellidoM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtApellidoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMActionPerformed(evt);
            }
        });
        jPanel4.add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 230, 30));

        txtTelefono.setEditable(false);
        txtTelefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        jPanel4.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 230, 30));

        txaObservacion.setEditable(false);
        txaObservacion.setColumns(20);
        txaObservacion.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        txaObservacion.setRows(5);
        txaObservacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane3.setViewportView(txaObservacion);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 240, 100));

        jPanel6.setBackground(new java.awt.Color(194, 36, 45));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtApoderadoDni.setEditable(false);
        txtApoderadoDni.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        txtApoderadoDni.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtApoderadoDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApoderadoDniActionPerformed(evt);
            }
        });
        jPanel6.add(txtApoderadoDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 150, -1));

        jLabel35.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Nombre");
        jPanel6.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel44.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("DNI");
        jPanel6.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txtApoderadoNom.setEditable(false);
        txtApoderadoNom.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        txtApoderadoNom.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtApoderadoNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApoderadoNomActionPerformed(evt);
            }
        });
        jPanel6.add(txtApoderadoNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 250, 110));

        txtDni.setEditable(false);
        txtDni.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtDni.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });
        jPanel4.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 230, 30));

        txtNombre.setEditable(false);
        txtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel4.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 229, 30));

        txtFechaDeNacimiento.setEditable(false);
        txtFechaDeNacimiento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtFechaDeNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaDeNacimientoActionPerformed(evt);
            }
        });
        jPanel4.add(txtFechaDeNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 229, 30));

        btnSeleccionAlumno.setBackground(new java.awt.Color(255, 255, 255));
        btnSeleccionAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        btnSeleccionAlumno.setText("SELECCIONAR ALUMNO");
        btnSeleccionAlumno.setBorder(null);
        btnSeleccionAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionAlumnoActionPerformed(evt);
            }
        });
        jPanel4.add(btnSeleccionAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 200, 40));

        txtSexo.setEditable(false);
        txtSexo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexoActionPerformed(evt);
            }
        });
        jPanel4.add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 230, 30));

        jLabel32.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("NOMBRE");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        jLabel34.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("APELLIDO MATERNO");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jLabel36.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("APODERADO");
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        jLabel37.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("APELLIDO PATERNO");
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel38.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("SEXO");
        jPanel4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel39.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("EDAD");
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        jLabel40.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("TELÉFONO");
        jPanel4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel41.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("FECHA DE NACIMIENTO");
        jPanel4.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        jLabel42.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("OBSERVACION");
        jPanel4.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel43.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("DNI");
        jPanel4.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 570, 510));

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(25, 0, 58));
        jLabel2.setText("Secretaria");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(25, 0, 58));
        jLabel5.setText("Información personal");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(25, 0, 58));
        jLabel7.setText("Datos de matrícula");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jPanel8.setBackground(new java.awt.Color(194, 36, 45));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSeccion.setEditable(false);
        txtSeccion.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        txtSeccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeccionActionPerformed(evt);
            }
        });
        jPanel8.add(txtSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 110, 30));

        txtNumGrado.setEditable(false);
        txtNumGrado.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        txtNumGrado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNumGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumGradoActionPerformed(evt);
            }
        });
        jPanel8.add(txtNumGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, 30));

        btnSeleccionGrado.setBackground(new java.awt.Color(255, 255, 255));
        btnSeleccionGrado.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 13)); // NOI18N
        btnSeleccionGrado.setText("SELECCIONAR GRADO");
        btnSeleccionGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionGradoActionPerformed(evt);
            }
        });
        jPanel8.add(btnSeleccionGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel28.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("SECCION");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jLabel31.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("GRADO");
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 280, 130));

        jPanel7.setBackground(new java.awt.Color(26, 2, 58));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdMatricula.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        txtIdMatricula.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtIdMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMatriculaActionPerformed(evt);
            }
        });
        txtIdMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdMatriculaKeyTyped(evt);
            }
        });
        jPanel7.add(txtIdMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 210, 30));

        jDate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(jDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 210, 30));

        jLabel30.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("FECHA");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel33.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("ID MATRICULA");
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 250, 150));

        jPanel9.setBackground(new java.awt.Color(196, 36, 45));
        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 190, 5));

        btnImprimirMatricula.setBackground(new java.awt.Color(255, 255, 255));
        btnImprimirMatricula.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        btnImprimirMatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-reporte.png"))); // NOI18N
        btnImprimirMatricula.setText("REPORTE");
        btnImprimirMatricula.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnImprimirMatricula.setEnabled(false);
        btnImprimirMatricula.setMinimumSize(new java.awt.Dimension(200, 200));
        btnImprimirMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirMatriculaActionPerformed(evt);
            }
        });
        jPanel1.add(btnImprimirMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 550, 180, -1));

        btnLista.setBackground(new java.awt.Color(255, 255, 255));
        btnLista.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        btnLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono_buscar.png"))); // NOI18N
        btnLista.setText("LISTA");
        btnLista.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLista.setMinimumSize(new java.awt.Dimension(200, 200));
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });
        jPanel1.add(btnLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 690, 180, 80));

        btnSalir4.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir4.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        btnSalir4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-salir.png"))); // NOI18N
        btnSalir4.setText("SALIR");
        btnSalir4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 810, 180, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 1050, 940));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtApoderadoDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApoderadoDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApoderadoDniActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtFechaDeNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaDeNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaDeNacimientoActionPerformed

    private void txtIdMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMatriculaActionPerformed

    private void txtDniSecretariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniSecretariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniSecretariaActionPerformed

    private void btnSeleccionAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionAlumnoActionPerformed
        // TODO add your handling code here:
        DialogListaAlumno d = new DialogListaAlumno();
        d.setVisible(true);
        try {
            a = AlumnoDAO.getInstancia().buscarAlumno(d.alumnoSelect.getDni());
             datosAlumno(a);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR: "+e.getMessage(),"",0);
        }catch(NullPointerException e){
            System.out.println("No se escogio ningún alumno");
        }
       
    }//GEN-LAST:event_btnSeleccionAlumnoActionPerformed
    
    private String generarId(){
        ArrayList <Matricula> lista = new ArrayList<>();
        try {
            lista = MatriculaDAO.getInstancia().mostrarMatriculas();
        } catch (SQLException ex) {
            System.out.println("Error SQL. Detalles: "+ex.getMessage());
        }
        int tamaño=lista.size();
        int aux;
        aux = tamaño;//Considerando que se le aumenta el elemento :v
        int orden=0;
        
        if(aux==0) orden=1;
        
        while (aux!=0){
            aux=aux/10;
            orden=orden+1;
        } //determino si es de 1,2,3 o 4 cifras
        
        String id="MAT";
        //GRA0000010
        for (int i = 0; i<10-3-orden;i++)//añade ceros hasta el tamaño menos el orden y los 3 caracteres de GRA
            id+="0";
        id+=String.valueOf(tamaño);
        return id;
    }
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int n = 0;
        try{
            cursos = CursoDAO.getInstancia().mostrarPorGrado(g.getIdGrado());
            n = MatriculaDAO.getInstancia().numMatriculadosPorGrado(g.getIdGrado());
        }catch(SQLException e){
            System.out.println("Error SQL. Detalles: "+e.getMessage());
        }
        if(n < g.getVacantes()){
        if(a!=null && s!=null && g!=null && !cursos.isEmpty()){
            String id = generarId();
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            String fechaNac = formato.format(jDate.getDate());
            m = new Matricula(id, fechaNac, a, g, s);
            try {
                
                if(MatriculaDAO.getInstancia().buscarMatriculaPorDniAlumno(a.getDni())==null){
                    cursos = CursoDAO.getInstancia().mostrarPorGrado(g.getIdGrado());
                    MD.insertarMatricula(m);
                    for (int i = 0; i < cursos.size(); i++) {
                        Bimestre bim1 = new Bimestre(cursos.get(i),1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"00000000");
                        Bimestre bim2 = new Bimestre(cursos.get(i),2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"00000000");
                        Bimestre bim3 = new Bimestre(cursos.get(i),3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"00000000");
                        Bimestre bim4 = new Bimestre(cursos.get(i),4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"00000000");
                        BimestreDAO.getInstancia().insertar(bim1,m.getAlumno());
                        BimestreDAO.getInstancia().insertar(bim2,m.getAlumno());
                        BimestreDAO.getInstancia().insertar(bim3,m.getAlumno());
                        BimestreDAO.getInstancia().insertar(bim4,m.getAlumno());                        
                    }
                    JOptionPane.showMessageDialog(null,"Matricula registrada.");
                    limpiarEntradas();
                }else{
                    JOptionPane.showMessageDialog(null, "Alumno ya matriculado en el año actual", "Advertencia", 2);
                    txtDni.requestFocus();
                }
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "ERROR: "+ex.getMessage());
            }
            
        }else{
            if(cursos.isEmpty()){
                JOptionPane.showMessageDialog(null,"El Grado y Sección seleccionado no presenta cursos registrados.\nPor favor, ingresar cursos en el grado"
                        + " antes de matricular a los alumnos", "Aviso",2);}
            else
                JOptionPane.showMessageDialog(null,"Seleccionar campos requeridos");
            
        }
        } else {
            JOptionPane.showMessageDialog(null,"Vacantes agotadas para el grado seleccionado","Aviso",2);
        }    
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        matbus = txtIdMatricula.getText().trim();
        try {
            if (matbus.equals("")) {
                JOptionPane.showMessageDialog(null, "Ingrese el código de matricula.");
            } else {
                m = MD.buscarMatricula(matbus);
                if (m != null) {
                    txtIdMatricula.setEnabled(false);
                    
                    java.util.Date fechaMat = new SimpleDateFormat("yyyy-MM-dd").parse(m.getFecha());
                    jDate.setDate(fechaMat);
                    
                    datosAlumno(m.getAlumno());
                    datosGrado(m.getGrado());
                    datosSecretaria(m.getSecretaria());
                    habilitar();
                } else {
                    JOptionPane.showMessageDialog(null, "Matricula no encontrada.");
                    limpiarEntradas();
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage(),"",0);
        } catch (ParseException ex) {
            Logger.getLogger(DialogRegistroMatricula.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        try {
            m = MD.buscarMatricula(matbus); 
            MD.eliminarMatricula(matbus, m.getAlumno().getDni());
            JOptionPane.showMessageDialog(this,"Matricula eliminada correctamente.");
            limpiarEntradas();
            desHabilitar();
            datosSecretaria(auxInicio);
            this.dispose();
        } catch (SQLException ex) {
            System.out.println("Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnImprimirMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirMatriculaActionPerformed
        // SELECCION RUTA
        String destino="Matricula_SGA"; // nombre por defecto
        JOptionPane.showMessageDialog(this, "Seleccione ubicación de archivo y el nombre respectivo","Guardar Archivo",1);
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showSaveDialog(this);
        if(result == JFileChooser.APPROVE_OPTION){
            try {
                destino = fileChooser.getSelectedFile().getCanonicalPath();
                destino+=".pdf";
            } catch (IOException ex) {
                Logger.getLogger(DialogRegistroMatricula.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        // CREACION DEL PDF
        Document document = new Document();
        try {
            PdfWriter.getInstance(document, new FileOutputStream(destino));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DialogRegistroMatricula.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(DialogRegistroMatricula.class.getName()).log(Level.SEVERE, null, ex);
        }
        document.open();
        
        // FUENTES
        Font fontNegrita_1 = new Font(FontFamily.HELVETICA, 22, Font.BOLD);
        Font fontNormal_1 = new Font(FontFamily.HELVETICA, 20, Font.NORMAL);
        Font fontNegrita_2 = new Font(FontFamily.HELVETICA, 16, Font.BOLD);
        Font fontNormal_2 = new Font(FontFamily.HELVETICA, 16, Font.NORMAL);
        Font fontColumnas = new Font(FontFamily.HELVETICA, 12, Font.BOLD);
        
        // TEXTOS
        Paragraph para1 = new Paragraph("Institucion Educativa Privada", fontNegrita_1);
        para1.setAlignment(Element.ALIGN_CENTER);
        Paragraph para2 = new Paragraph("CEPAS", fontNegrita_1);
        para2.setAlignment(Element.ALIGN_CENTER);
        Paragraph para3 = new Paragraph("Ficha de Matrícula - SGA",fontNormal_1);
        para3.setAlignment(Element.ALIGN_CENTER);
        
        Image foto = null;
        try {
            foto = Image.getInstance(getClass().getResource("/img/icon_log.png"));
        } catch (Exception ex2) {
            Logger.getLogger(DialogRegistroMatricula.class.getName()).log(Level.SEVERE, null, ex2);
        }
	foto.setAlignment(Chunk.ALIGN_MIDDLE);
        
        
        Paragraph para4 = new Paragraph("ID Matrícula: ",fontNegrita_2);
        para4.setFont(fontNormal_2);
        para4.add(m.getId());
        
        Paragraph para5 = new Paragraph("Fecha: ",fontNegrita_2);
        para5.setFont(fontNormal_2);
        para5.add(m.getFecha());
        
        Paragraph para6 = new Paragraph("Alumno: ",fontNegrita_2);
        para6.setFont(fontNormal_2);
        para6.add(m.getAlumno().nombreCompleto());
        para6.setFont(fontNegrita_2);
        para6.add("    DNI: ");
        para6.setFont(fontNormal_2);
        para6.add(m.getAlumno().getDni());
        
        Paragraph para7 = new Paragraph("Grado: ",fontNegrita_2);
        para7.setFont(fontNormal_2);
        para7.add(String.valueOf(m.getGrado().getNumGrado()));
        para7.setFont(fontNegrita_2);
        para7.add("    Sección: ");
        para7.setFont(fontNormal_2);
        para7.add(m.getGrado().getSeccion());
        
        Paragraph para8 = new Paragraph("Secretaria: ",fontNegrita_2);
        para8.setFont(fontNormal_2);
        para8.add(m.getSecretaria().nombreCompleto());
        
        
        // TABLA CURSOS
       Paragraph para8_2 = new Paragraph("Cursos registrados: ",fontNegrita_2);
       PdfPTable tabla = new PdfPTable(3);
       PdfPCell idCurso = new PdfPCell(new Paragraph("ID Curso",fontColumnas)); 
       PdfPCell nombre = new PdfPCell(new Paragraph("Nombre",fontColumnas));
       PdfPCell profesor = new PdfPCell(new Paragraph("Profesor",fontColumnas));
       tabla.addCell(idCurso);
       tabla.addCell(nombre);
       tabla.addCell(profesor);
        try {
            cursos = CursoDAO.getInstancia().mostrarPorGrado(m.getGrado().getIdGrado());

        } catch (SQLException ex) {
            Logger.getLogger(DialogRegistroMatricula.class.getName()).log(Level.SEVERE, null, ex);
        }
       for (int i = 0; i < cursos.size(); i++)
       {
	tabla.addCell(cursos.get(i).getIdCurso());
        tabla.addCell(cursos.get(i).getNombre());
        tabla.addCell(cursos.get(i).getDocente().nombreCompleto());
       }
       
       //FIRMA
       Paragraph para9 = new Paragraph("____________________    ",fontNormal_2);
       para9.setAlignment(Element.ALIGN_BOTTOM);
       para9.setAlignment(Element.ALIGN_RIGHT);
       Paragraph para10 = new Paragraph("Secretaria               ",fontNormal_2);
       para10.setAlignment(Element.ALIGN_BOTTOM);
       para10.setAlignment(Element.ALIGN_RIGHT);
       
       
       // Agregar todos los elementos previamente creados
        try {
            document.add(para1);
            document.add(para2);
            document.add(para3);
            document.add(foto);
            document.add(Chunk.NEWLINE);
            document.add(para4);
            document.add(para5);
            document.add(para6);
            document.add(para7);
            document.add(para8);
            document.add(para8_2);
            document.add(new Paragraph("\n"));
            document.add(tabla);
            
            document.add(Chunk.NEWLINE);
            
            document.add(para9);
            document.add(para10);
        } catch (DocumentException ex3) {
            Logger.getLogger(DialogRegistroMatricula.class.getName()).log(Level.SEVERE, null, ex3);
        }
        
        // CERRAR DOCUMENTO y su edicion
        document.close();
        
        // ABRIR ARCHIVO
        File objetofile = new File (destino);
        try {
            Desktop.getDesktop().open(objetofile);
        } catch (IOException ex4) {
            Logger.getLogger(DialogRegistroMatricula.class.getName()).log(Level.SEVERE, null, ex4);
        }
    }//GEN-LAST:event_btnImprimirMatriculaActionPerformed

    private void btnSalir4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir4ActionPerformed
        a= null;
        dispose();
    }//GEN-LAST:event_btnSalir4ActionPerformed

    private void txtSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeccionActionPerformed

    private void txtNumGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumGradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumGradoActionPerformed

    private void btnSeleccionGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionGradoActionPerformed
        // TODO add your handling code here:
        DialogGrado f = new DialogGrado();
        f.setVisible(true);
      
        try {
          g = GradoDAO.getInstancia().buscarGrado(f.gradoSelec.getIdGrado());
          datosGrado(g);
        } catch (SQLException e) {
            System.out.println("ERROR: "+e.getMessage());
        }catch(NullPointerException e){
            System.out.println("NullPointerException en seleccionar grado");
        }
        
    }//GEN-LAST:event_btnSeleccionGradoActionPerformed

    private void txtApellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPActionPerformed

    private void txtSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexoActionPerformed

    private void txtIdMatriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdMatriculaKeyTyped
        // TODO add your handling code here:
       if (txtIdMatricula.getText().length()==10){
            evt.consume(); 
        }
    }//GEN-LAST:event_txtIdMatriculaKeyTyped

    private void txtNombreSecretariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreSecretariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreSecretariaActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        DialogMatriculas dm = new DialogMatriculas();
        dm.setVisible(true);
        
    }//GEN-LAST:event_btnListaActionPerformed

    private void txtApoderadoNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApoderadoNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApoderadoNomActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DialogRegistroMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DialogRegistroMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DialogRegistroMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DialogRegistroMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DialogRegistroMatricula dialog = new DialogRegistroMatricula();
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimirMatricula;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnSalir4;
    private javax.swing.JButton btnSeleccionAlumno;
    private javax.swing.JButton btnSeleccionGrado;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txaObservacion;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtApoderadoDni;
    private javax.swing.JTextField txtApoderadoNom;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtDniSecretaria;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFechaDeNacimiento;
    private javax.swing.JTextField txtIdMatricula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreSecretaria;
    private javax.swing.JTextField txtNumGrado;
    private javax.swing.JTextField txtSeccion;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
