/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import entidad.Grado;
import datos.GradoDAO;
import datos.MatriculaDAO;
import java.awt.Cursor;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Johann
 */
public class DialogGrado extends javax.swing.JDialog {

    DefaultTableModel modelo = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    Grado gradoBusc = null;
    Grado gradoSelec=null;
    public DialogGrado() {
        super(FrmInicioSecretaria.getInstancia(), true);
        initComponents();
        setLocationRelativeTo(null);
        SpinnerNumberModel nm = new SpinnerNumberModel();
        nm.setMaximum(5);
        nm.setMinimum(1);
        nm.setValue(1);
        spnrGrado.setModel(nm);
        
        try {
            GradoDAO.getInstancia().mostrar(GradoDAO.getInstancia().mostrarGrados(), modelo);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        }
    }
    
    public void setB(boolean b){ 
        if(b){ 
           btnSeleccionar.setVisible(b); 
        }else btnSeleccionar.setVisible(b);  
    }
    
    public void setScaledPhoto(JLabel lbl, String route){
        ImageIcon img = new ImageIcon(route);
        Icon icono = new ImageIcon(img.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), 1));
        lbl.setIcon(icono);
    }
    private void activar(){
        btnActualizar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnActualizar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnEliminar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        btnRegistrar.setEnabled(false);
        btnConsultar.setEnabled(false);
        txtID.setEnabled(false);
        btnRegistrar.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        btnConsultar.setCursor(new Cursor(Cursor.WAIT_CURSOR));
    }
    
    private void desactivar(){
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnActualizar.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        btnEliminar.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        
        btnRegistrar.setEnabled(true);
        btnConsultar.setEnabled(true);
        txtID.setEnabled(true);
        btnRegistrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnConsultar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
       
    private void limpiar(){
        txtID.setText("");
        txtVacantes.setText("");
        spnrGrado.setValue(1);
        cboSeccion.setSelectedIndex(0);
        txtID.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtBuscarPorID = new javax.swing.JTextField();
        cboOrdenar = new javax.swing.JComboBox<>();
        btnSeleccionar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pnlBack = new javax.swing.JPanel();
        pnlSide = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cboSeccion = new javax.swing.JComboBox<>();
        spnrGrado = new javax.swing.JSpinner();
        txtVacantes = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(194, 36, 45));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        jTable1.setModel(modelo);
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(22);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 940, 400));

        txtBuscarPorID.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        txtBuscarPorID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtBuscarPorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarPorIDActionPerformed(evt);
            }
        });
        txtBuscarPorID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarPorIDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarPorIDKeyTyped(evt);
            }
        });
        jPanel1.add(txtBuscarPorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 170, 30));

        cboOrdenar.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        cboOrdenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "NÚMERO DE GRADO", "VACANTES", "SECCIÓN" }));
        cboOrdenar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cboOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboOrdenarActionPerformed(evt);
            }
        });
        jPanel1.add(cboOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, 180, 30));

        btnSeleccionar.setBackground(new java.awt.Color(255, 255, 255));
        btnSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-selecc.png"))); // NOI18N
        btnSeleccionar.setText("SELECCIONAR");
        btnSeleccionar.setBorder(null);
        btnSeleccionar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSeleccionar.setMinimumSize(new java.awt.Dimension(200, 200));
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 40, 150, 40));

        btnRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save_37110.png"))); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setBorder(null);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRegistrar.setMinimumSize(new java.awt.Dimension(200, 200));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 170, 50));

        btnConsultar.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultar.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono-Consulta.png"))); // NOI18N
        btnConsultar.setText("CONSULTAR");
        btnConsultar.setBorder(null);
        btnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultar.setMinimumSize(new java.awt.Dimension(200, 200));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 170, 50));

        btnActualizar.setBackground(new java.awt.Color(255, 255, 255));
        btnActualizar.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono-Actualizar.png"))); // NOI18N
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setBorder(null);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnActualizar.setEnabled(false);
        btnActualizar.setMinimumSize(new java.awt.Dimension(200, 200));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 170, 50));

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-Delete.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorder(null);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminar.setEnabled(false);
        btnEliminar.setMinimumSize(new java.awt.Dimension(200, 200));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 170, 50));

        btnLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-clean.png"))); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorder(null);
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 170, 50));

        jLabel13.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Ordenar");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, -1, -1));

        jLabel16.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Buscar por ID");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 1220, 530));

        pnlBack.setBackground(new java.awt.Color(231, 235, 244));
        pnlBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSide.setBackground(new java.awt.Color(26, 2, 58));
        pnlBack.add(pnlSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 120, 830));

        jPanel6.setBackground(new java.awt.Color(196, 36, 45));
        pnlBack.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 200, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 54)); // NOI18N
        jLabel1.setText("GRADOS");
        pnlBack.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jPanel3.setBackground(new java.awt.Color(26, 2, 58));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboSeccion.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        cboSeccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "A", "B", "C", "D" }));
        cboSeccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(cboSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 160, 30));

        spnrGrado.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        spnrGrado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(spnrGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 48, 170, 30));

        txtVacantes.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        txtVacantes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtVacantes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVacantesKeyTyped(evt);
            }
        });
        jPanel3.add(txtVacantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 120, -1));

        txtID.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        txtID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDKeyTyped(evt);
            }
        });
        jPanel3.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, -1));

        jLabel11.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SECCIÓN");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        jLabel12.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ID");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel14.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("VACANTES");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel15.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("GRADO ACADÉMICO");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        pnlBack.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 690, 90));

        getContentPane().add(pnlBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        try {
            GradoDAO.getInstancia().eliminar(gradoBusc.getIdGrado());
            JOptionPane.showMessageDialog(this,"Grado eliminado correctamente.");
            limpiar();
            desactivar();
            GradoDAO.getInstancia().mostrar(GradoDAO.getInstancia().mostrarGrados(), modelo);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Acción restringida: No se puede eliminar un grado en la cuál hay alumnos matriculado", "Advertencia", 0);
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    
    private String generarId(){
        ArrayList <Grado> lista = new ArrayList<>();
        try {
            lista = GradoDAO.getInstancia().mostrarGrados();
        } catch (SQLException ex) {
            System.out.println("Error SQL. Detalles: "+ex.getMessage());
        }
        int tamaño=lista.size();
        int aux;
        aux = tamaño;//Considerando que se le aumenta el elemento :v
        int orden=0;
        
        if(aux==0) orden=1;
        
        while (aux!=0){
            aux=aux/10;
            orden=orden+1;
        } //determino si es de 1,2,3 o 4 cifras
        String id="GRA";
        //GRA0000010
        for (int i = 0; i<10-3-orden;i++)//añade ceros hasta el tamaño menos el orden y los 3 caracteres de GRA
            id+="0";
        id+=String.valueOf(tamaño);
        return id;
    }
    
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        try {
            String id = generarId().trim();
            int vacantes = Integer.parseInt(txtVacantes.getText());
            int numgrado= (int) spnrGrado.getValue();
            
            String seccion = null;
            switch(cboSeccion.getSelectedIndex()){
                case 1: seccion="A"; break;
                case 2: seccion="B"; break;
                case 3: seccion="C"; break;
                case 4: seccion="D"; break;
            }
            Grado x = new Grado(id, numgrado, vacantes, seccion);
            GradoDAO.getInstancia().insertar(x);
            GradoDAO.getInstancia().mostrar(GradoDAO.getInstancia().mostrarGrados(), modelo);
            limpiar();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Revise las entradas. No debe haber ningún campo vacío");
        }catch(NumberFormatException e){
            System.out.println("NumberFormatException");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        String id = txtID.getText().trim();
        try {
            if(id.equals("")){
                JOptionPane.showMessageDialog(null,"Ingrese un ID para consultas");
            }else{ 
                gradoBusc = GradoDAO.getInstancia().buscarGrado(id);
                if(gradoBusc!=null){
                    txtVacantes.setText(String.valueOf(gradoBusc.getVacantes()));
                    spnrGrado.setValue(gradoBusc.getNumGrado());
                    switch(gradoBusc.getSeccion()){
                        case "A": cboSeccion.setSelectedIndex(1);break;
                        case "B": cboSeccion.setSelectedIndex(2);break;
                        case "C": cboSeccion.setSelectedIndex(3);break;
                        case "D": cboSeccion.setSelectedIndex(4);break;
                    }
                    activar();
                    
                }else JOptionPane.showMessageDialog(null,"No se encuentra en el registro");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try { 
            String id = txtID.getText().trim(); 
            int vacantes = Integer.parseInt(txtVacantes.getText()); 
            int numgrado= (int) spnrGrado.getValue(); 
             
            String seccion = null; 
            switch(cboSeccion.getSelectedIndex()){ 
                case 1: seccion="A"; break; 
                case 2: seccion="B"; break; 
                case 3: seccion="C"; break; 
                case 4: seccion="D"; break; 
            } 
            if(vacantes >= MatriculaDAO.getInstancia().numMatriculadosPorGrado(id)){ 
                Grado x = new Grado(id, numgrado, vacantes, seccion); 
                GradoDAO.getInstancia().actualizar(gradoBusc.getIdGrado(),x); 
                GradoDAO.getInstancia().mostrar(GradoDAO.getInstancia().mostrarGrados(), modelo); 
                limpiar(); 
                desactivar(); 
            }else{ 
                JOptionPane.showMessageDialog(null,"Debe eliminar estudiantes matriculados para reducir las vacantes\nAlumnos matriculados: "+MatriculaDAO.getInstancia().numMatriculadosPorGrado(id),"Advertencia",2); 
                txtVacantes.requestFocus(); 
            } 
        } catch (SQLException e) { 
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage()); 
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        if(i!=-1){
            gradoSelec = new Grado();
            gradoSelec.setIdGrado(modelo.getValueAt(i,0).toString());
            this.dispose();
        }else JOptionPane.showMessageDialog(null, "Seleccione un elemento de la tabla");
        
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void txtBuscarPorIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarPorIDKeyReleased
        // TODO add your handling code here:
        try {
            if(txtBuscarPorID.getText().equals(""))
                 GradoDAO.getInstancia().mostrar(GradoDAO.getInstancia().mostrarGrados(), modelo);  
            else
                GradoDAO.getInstancia().mostrar(GradoDAO.getInstancia().buscarPorID(txtBuscarPorID.getText().trim()),modelo);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage(),"",0);
        }
    }//GEN-LAST:event_txtBuscarPorIDKeyReleased

    private void cboOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboOrdenarActionPerformed
        // TODO add your handling code here:
        try {
            switch(cboOrdenar.getSelectedIndex()){
                case 0: GradoDAO.getInstancia().mostrar(GradoDAO.getInstancia().mostrarGrados(), modelo); break;
                case 1: GradoDAO.getInstancia().mostrar(GradoDAO.getInstancia().ordenar("numGrado"), modelo); break;
                case 2: GradoDAO.getInstancia().mostrar(GradoDAO.getInstancia().ordenar("vacantes"), modelo); break;
                case 3: GradoDAO.getInstancia().mostrar(GradoDAO.getInstancia().ordenar("seccion"), modelo); break;
                                         
            }
         
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        }
       
    }//GEN-LAST:event_cboOrdenarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
        desactivar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtVacantesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVacantesKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
               
        if(!Character.isDigit(c)){
             evt.consume();
         }
        
    }//GEN-LAST:event_txtVacantesKeyTyped

    private void txtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyTyped
        if (txtID.getText().length()==10){
            evt.consume(); 
        }
    }//GEN-LAST:event_txtIDKeyTyped

    private void txtBuscarPorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarPorIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarPorIDActionPerformed

    private void txtBuscarPorIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarPorIDKeyTyped
        if (txtBuscarPorID.getText().length()==10){
            evt.consume(); 
        }
    }//GEN-LAST:event_txtBuscarPorIDKeyTyped

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DialogGrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DialogGrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DialogGrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DialogGrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DialogGrado dialog = new DialogGrado(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JComboBox<String> cboOrdenar;
    private javax.swing.JComboBox<String> cboSeccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JPanel pnlSide;
    private javax.swing.JSpinner spnrGrado;
    private javax.swing.JTextField txtBuscarPorID;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtVacantes;
    // End of variables declaration//GEN-END:variables
}
