/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import entidad.*;
import java.awt.Color;
import java.awt.Frame;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author hiro
 */
public class FrmInicioDocente extends javax.swing.JFrame {
    int xCursor, yCursor;
    Docente docenteLog = null;
    /**
     * Creates new form FrmInicioSecretaria
     */
    private static FrmInicioDocente instancia;
    public static FrmInicioDocente getInstancia(){
        if(instancia==null)
            instancia=new FrmInicioDocente();
        return instancia;
    }
    public FrmInicioDocente() {
        initComponents();
        setLocationRelativeTo(null);
        ImageIcon iconoFrm = new ImageIcon(getClass().getResource("/img/logoPrincipal.png"));
        this.setIconImage(iconoFrm.getImage()); 
        
    }
    
//    public void setScaledPhoto(JLabel lbl, String route){
//        ImageIcon img = new ImageIcon(route);
//        Icon icono = new ImageIcon(img.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), 1));
//        lbl.setIcon(icono);
//    }
    public void setDocenteLog(Docente d){
        docenteLog = d;
        lblNombreDocente.setText(docenteLog.getApellido_p()+" "+docenteLog.getApellido_m()+", "+docenteLog.getNombre());
        lblNombreDocente.setSize(10, 10);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBack = new javax.swing.JPanel();
        pnlUpper = new javax.swing.JPanel();
        pnlMin = new javax.swing.JPanel();
        lblMin = new javax.swing.JLabel();
        pnlExit = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        lblNombreDocente = new javax.swing.JLabel();
        pnlSide = new javax.swing.JPanel();
        pnlPerfil = new javax.swing.JPanel();
        lblSecretaria = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        pnlLinea = new javax.swing.JPanel();
        pnlRecord = new javax.swing.JPanel();
        lblGrado = new javax.swing.JLabel();
        pnlMatriculas = new javax.swing.JPanel();
        lblCurso = new javax.swing.JLabel();
        pnlListas = new javax.swing.JPanel();
        lblListas = new javax.swing.JLabel();
        pnlCerrarSesion = new javax.swing.JPanel();
        lblAlumno = new javax.swing.JLabel();
        lblDocIni = new javax.swing.JLabel();
        lblLogoMenu = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBack.setBackground(new java.awt.Color(26, 2, 58));
        pnlBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlUpper.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlUpperMouseDragged(evt);
            }
        });
        pnlUpper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlUpperMousePressed(evt);
            }
        });
        pnlUpper.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMin.setBackground(new java.awt.Color(255, 255, 255));
        pnlMin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMin.setFont(new java.awt.Font("Yu Gothic", 0, 16)); // NOI18N
        lblMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMin.setText("_");
        lblMin.setToolTipText("");
        lblMin.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinMouseExited(evt);
            }
        });
        pnlMin.add(lblMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        pnlUpper.add(pnlMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 0, 70, 30));

        pnlExit.setBackground(new java.awt.Color(255, 255, 255));
        pnlExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblExit.setBackground(new java.awt.Color(255, 255, 255));
        lblExit.setFont(new java.awt.Font("Yu Gothic", 0, 16)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("X");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        pnlExit.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        pnlUpper.add(pnlExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 70, 40));

        lblNombreDocente.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lblNombreDocente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombreDocente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlUpper.add(lblNombreDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 460, 30));

        pnlBack.add(pnlUpper, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1030, 30));

        pnlSide.setBackground(new java.awt.Color(255, 255, 255));
        pnlSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPerfil.setBackground(new java.awt.Color(26, 2, 58));
        pnlPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPerfilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlPerfilMouseExited(evt);
            }
        });

        lblSecretaria.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        lblSecretaria.setForeground(new java.awt.Color(255, 255, 255));
        lblSecretaria.setText("Perfil");
        lblSecretaria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSecretaria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlPerfilLayout = new javax.swing.GroupLayout(pnlPerfil);
        pnlPerfil.setLayout(pnlPerfilLayout);
        pnlPerfilLayout.setHorizontalGroup(
            pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPerfilLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(lblSecretaria)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        pnlPerfilLayout.setVerticalGroup(
            pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSecretaria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        pnlSide.add(pnlPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 260, 35));

        lblTitulo.setFont(new java.awt.Font("Yu Gothic", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(26, 2, 58));
        lblTitulo.setText("Menú de control");
        pnlSide.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 210, 40));

        pnlLinea.setBackground(new java.awt.Color(194, 36, 45));

        javax.swing.GroupLayout pnlLineaLayout = new javax.swing.GroupLayout(pnlLinea);
        pnlLinea.setLayout(pnlLineaLayout);
        pnlLineaLayout.setHorizontalGroup(
            pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        pnlLineaLayout.setVerticalGroup(
            pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        pnlSide.add(pnlLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 80, 5));

        pnlRecord.setBackground(new java.awt.Color(26, 2, 58));
        pnlRecord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlRecordMouseExited(evt);
            }
        });

        lblGrado.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        lblGrado.setForeground(new java.awt.Color(255, 255, 255));
        lblGrado.setText("Cursos");
        lblGrado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGrado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlRecordLayout = new javax.swing.GroupLayout(pnlRecord);
        pnlRecord.setLayout(pnlRecordLayout);
        pnlRecordLayout.setHorizontalGroup(
            pnlRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecordLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(lblGrado)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        pnlRecordLayout.setVerticalGroup(
            pnlRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGrado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        pnlSide.add(pnlRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 260, 35));

        pnlMatriculas.setBackground(new java.awt.Color(26, 2, 58));
        pnlMatriculas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlMatriculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMatriculasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMatriculasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMatriculasMouseExited(evt);
            }
        });

        lblCurso.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        lblCurso.setForeground(new java.awt.Color(255, 255, 255));
        lblCurso.setText("Registros");
        lblCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCurso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlMatriculasLayout = new javax.swing.GroupLayout(pnlMatriculas);
        pnlMatriculas.setLayout(pnlMatriculasLayout);
        pnlMatriculasLayout.setHorizontalGroup(
            pnlMatriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMatriculasLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(lblCurso)
                .addGap(93, 93, 93))
        );
        pnlMatriculasLayout.setVerticalGroup(
            pnlMatriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        pnlSide.add(pnlMatriculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 260, 35));

        pnlListas.setBackground(new java.awt.Color(26, 2, 58));
        pnlListas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlListas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlListasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlListasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlListasMouseExited(evt);
            }
        });

        lblListas.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        lblListas.setForeground(new java.awt.Color(255, 255, 255));
        lblListas.setText("Listas");
        lblListas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblListas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlListasLayout = new javax.swing.GroupLayout(pnlListas);
        pnlListas.setLayout(pnlListasLayout);
        pnlListasLayout.setHorizontalGroup(
            pnlListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListasLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(lblListas)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        pnlListasLayout.setVerticalGroup(
            pnlListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblListas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        pnlSide.add(pnlListas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 260, 35));

        pnlCerrarSesion.setBackground(new java.awt.Color(26, 2, 58));
        pnlCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlCerrarSesionMouseExited(evt);
            }
        });

        lblAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        lblAlumno.setForeground(new java.awt.Color(255, 255, 255));
        lblAlumno.setText("Cerrar Sesión");
        lblAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAlumno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlCerrarSesionLayout = new javax.swing.GroupLayout(pnlCerrarSesion);
        pnlCerrarSesion.setLayout(pnlCerrarSesionLayout);
        pnlCerrarSesionLayout.setHorizontalGroup(
            pnlCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCerrarSesionLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(lblAlumno)
                .addGap(80, 80, 80))
        );
        pnlCerrarSesionLayout.setVerticalGroup(
            pnlCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        pnlSide.add(pnlCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 260, 35));

        lblDocIni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/docIni.png"))); // NOI18N
        pnlSide.add(lblDocIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        pnlBack.add(pnlSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 660));

        lblLogoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoPrincipal.png"))); // NOI18N
        lblLogoMenu.setText("jLabel1");
        pnlBack.add(lblLogoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 500, 140, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CepasSinFondo.png"))); // NOI18N
        lblLogo.setText("jLabel1");
        pnlBack.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 230, 210));

        getContentPane().add(pnlBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1040, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPerfilMouseClicked
          DialogDocentePerfil ap = new DialogDocentePerfil();
          ap.setDocente(docenteLog);
          ap.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_pnlPerfilMouseClicked

    private void pnlPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPerfilMouseEntered
        pnlPerfil.setBackground(new Color(168, 181, 240));
        lblSecretaria.setForeground(new Color(26, 2, 58));
    }//GEN-LAST:event_pnlPerfilMouseEntered

    private void pnlPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPerfilMouseExited
        pnlPerfil.setBackground(new Color(26, 2, 58));
        lblSecretaria.setForeground(Color.WHITE);
    }//GEN-LAST:event_pnlPerfilMouseExited

    private void pnlRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRecordMouseClicked
        DialogCursosFromDocente c = new DialogCursosFromDocente();
        c.setD(docenteLog);
        c.setVisible(true);
    }//GEN-LAST:event_pnlRecordMouseClicked

    private void pnlRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRecordMouseEntered
        pnlRecord.setBackground(new Color(168, 181, 240));
        lblGrado.setForeground(new Color(26, 2, 58));
    }//GEN-LAST:event_pnlRecordMouseEntered

    private void pnlRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRecordMouseExited
        pnlRecord.setBackground(new Color(26, 2, 58));
        lblGrado.setForeground(Color.WHITE);
    }//GEN-LAST:event_pnlRecordMouseExited

    private void pnlUpperMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUpperMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xCursor, y - yCursor);
    }//GEN-LAST:event_pnlUpperMouseDragged

    private void pnlUpperMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUpperMousePressed
        xCursor = evt.getX();
        yCursor = evt.getY();
    }//GEN-LAST:event_pnlUpperMousePressed

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        pnlExit.setBackground(Color.RED);
        lblExit.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        pnlExit.setBackground(Color.WHITE);
        lblExit.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblExitMouseExited

    private void lblMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_lblMinMouseClicked

    private void lblMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseEntered
        pnlMin.setBackground(new Color(240,240,240));
        lblMin.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblMinMouseEntered

    private void lblMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseExited
        pnlMin.setBackground(Color.WHITE);
        lblMin.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblMinMouseExited

    private void pnlMatriculasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMatriculasMouseClicked
        DialogRegistro dReg = new DialogRegistro(docenteLog);
        dReg.setVisible(true);
    }//GEN-LAST:event_pnlMatriculasMouseClicked

    private void pnlMatriculasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMatriculasMouseEntered
        pnlMatriculas.setBackground(new Color(168, 181, 240));
        lblCurso.setForeground(new Color(26, 2, 58));
    }//GEN-LAST:event_pnlMatriculasMouseEntered

    private void pnlMatriculasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMatriculasMouseExited
        pnlMatriculas.setBackground(new Color(26, 2, 58));
        lblCurso.setForeground(Color.WHITE);
    }//GEN-LAST:event_pnlMatriculasMouseExited

    private void pnlListasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlListasMouseClicked
        DialogListasFromDocente dlfd = new DialogListasFromDocente();
        dlfd.setD(docenteLog);
        dlfd.setVisible(true);
    }//GEN-LAST:event_pnlListasMouseClicked

    private void pnlListasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlListasMouseEntered
        pnlListas.setBackground(new Color(168, 181, 240));
        lblListas.setForeground(new Color(26, 2, 58));
    }//GEN-LAST:event_pnlListasMouseEntered

    private void pnlListasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlListasMouseExited
        pnlListas.setBackground(new Color(26, 2, 58));
        lblListas.setForeground(Color.WHITE);
    }//GEN-LAST:event_pnlListasMouseExited

    private void pnlCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCerrarSesionMouseClicked
        docenteLog = null;
        this.dispose();
        FrmLogin l = new FrmLogin();
        l.setUsuario(null);
        l.setVisible(true);
    }//GEN-LAST:event_pnlCerrarSesionMouseClicked

    private void pnlCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCerrarSesionMouseEntered
        pnlCerrarSesion.setBackground(new Color(168, 181, 240));
        lblAlumno.setForeground(new Color(26, 2, 58));
    }//GEN-LAST:event_pnlCerrarSesionMouseEntered

    private void pnlCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCerrarSesionMouseExited
        pnlCerrarSesion.setBackground(new Color(26, 2, 58));
        lblAlumno.setForeground(Color.WHITE);
    }//GEN-LAST:event_pnlCerrarSesionMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicioDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicioDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicioDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicioDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInicioDocente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAlumno;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDocIni;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblGrado;
    private javax.swing.JLabel lblListas;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogoMenu;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblNombreDocente;
    private javax.swing.JLabel lblSecretaria;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JPanel pnlCerrarSesion;
    private javax.swing.JPanel pnlExit;
    private javax.swing.JPanel pnlLinea;
    private javax.swing.JPanel pnlListas;
    private javax.swing.JPanel pnlMatriculas;
    private javax.swing.JPanel pnlMin;
    private javax.swing.JPanel pnlPerfil;
    private javax.swing.JPanel pnlRecord;
    private javax.swing.JPanel pnlSide;
    private javax.swing.JPanel pnlUpper;
    // End of variables declaration//GEN-END:variables
}
