/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import entidad.Secretaria;
import java.awt.Color;
import java.awt.Frame;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author hiro
 */
public class FrmInicioSecretaria extends javax.swing.JFrame {
    int xCursor, yCursor;
    private Secretaria secretariaLog = null;
    /**
     * Creates new form FrmInicioSecretaria
     */
    private static FrmInicioSecretaria instancia;
    public static FrmInicioSecretaria getInstancia(){
        if(instancia==null)
            instancia=new FrmInicioSecretaria();
        return instancia;
    }
    public FrmInicioSecretaria() {
        initComponents();
        setLocationRelativeTo(null);
        setScaledPhoto(lblLogo, "src/img/CepasSinFondo.png");
        
        ImageIcon iconoFrm = new ImageIcon(getClass().getResource("/img/logoPrincipal.png"));
        this.setIconImage(iconoFrm.getImage()); 
    }
    
    public void setScaledPhoto(JLabel lbl, String route){
        ImageIcon img = new ImageIcon(getClass().getResource("/img/CepasSinFondo.png"));
        Icon icono = new ImageIcon(img.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), 1));
        lbl.setIcon(icono);
    }
    
    public void setSecretariaLog(Secretaria s){
        secretariaLog = s;
        lblNombreSecretaria.setText(secretariaLog.getApellido_p()+" "+secretariaLog.getApellido_m()+", "+secretariaLog.getNombre());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBack = new javax.swing.JPanel();
        pnlUpper = new javax.swing.JPanel();
        pnlMin = new javax.swing.JPanel();
        lblMin = new javax.swing.JLabel();
        pnlExit = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        lblNombreSecretaria = new javax.swing.JLabel();
        pnlSide = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        pnlSecretaria = new javax.swing.JPanel();
        lblSecretaria = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        pnlLinea = new javax.swing.JPanel();
        pnlGrado = new javax.swing.JPanel();
        lblGrado = new javax.swing.JLabel();
        pnlCurso = new javax.swing.JPanel();
        lblCurso = new javax.swing.JLabel();
        pnlDocente = new javax.swing.JPanel();
        lblDocente = new javax.swing.JLabel();
        pnlAlumno = new javax.swing.JPanel();
        lblAlumno = new javax.swing.JLabel();
        pnlApoderado = new javax.swing.JPanel();
        lblApoderado = new javax.swing.JLabel();
        pnlMatriculas = new javax.swing.JPanel();
        lblMatriculas = new javax.swing.JLabel();
        pnlCerrarSesion = new javax.swing.JPanel();
        lblCerrarSesion = new javax.swing.JLabel();
        lblLogoMenu = new javax.swing.JLabel();
        pnlPerfil = new javax.swing.JPanel();
        lblPerfil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBack.setBackground(new java.awt.Color(26, 2, 58));
        pnlBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlUpper.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlUpperMouseDragged(evt);
            }
        });
        pnlUpper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlUpperMousePressed(evt);
            }
        });
        pnlUpper.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMin.setBackground(new java.awt.Color(255, 255, 255));
        pnlMin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMin.setFont(new java.awt.Font("Yu Gothic", 0, 16)); // NOI18N
        lblMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMin.setText("_");
        lblMin.setToolTipText("");
        lblMin.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinMouseExited(evt);
            }
        });
        pnlMin.add(lblMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        pnlUpper.add(pnlMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 0, 70, 30));

        pnlExit.setBackground(new java.awt.Color(255, 255, 255));
        pnlExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblExit.setBackground(new java.awt.Color(255, 255, 255));
        lblExit.setFont(new java.awt.Font("Yu Gothic", 0, 16)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("X");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        pnlExit.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        pnlUpper.add(pnlExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 70, 40));

        lblNombreSecretaria.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lblNombreSecretaria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlUpper.add(lblNombreSecretaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 0, 300, 30));

        pnlBack.add(pnlUpper, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1030, 30));

        pnlSide.setBackground(new java.awt.Color(255, 255, 255));
        pnlSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CepasSinFondo.png"))); // NOI18N
        lblLogo.setText("jLabel1");
        pnlSide.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 150, 150));

        pnlSecretaria.setBackground(new java.awt.Color(26, 2, 58));
        pnlSecretaria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSecretaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSecretariaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSecretariaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSecretariaMouseExited(evt);
            }
        });

        lblSecretaria.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        lblSecretaria.setForeground(new java.awt.Color(255, 255, 255));
        lblSecretaria.setText("Secretaria");
        lblSecretaria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSecretaria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlSecretariaLayout = new javax.swing.GroupLayout(pnlSecretaria);
        pnlSecretaria.setLayout(pnlSecretariaLayout);
        pnlSecretariaLayout.setHorizontalGroup(
            pnlSecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSecretariaLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(lblSecretaria)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        pnlSecretariaLayout.setVerticalGroup(
            pnlSecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSecretaria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        pnlSide.add(pnlSecretaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 260, 35));

        lblTitulo.setFont(new java.awt.Font("Yu Gothic", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(26, 2, 58));
        lblTitulo.setText("Menú de control");
        pnlSide.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 190, 40));

        pnlLinea.setBackground(new java.awt.Color(194, 36, 45));

        javax.swing.GroupLayout pnlLineaLayout = new javax.swing.GroupLayout(pnlLinea);
        pnlLinea.setLayout(pnlLineaLayout);
        pnlLineaLayout.setHorizontalGroup(
            pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        pnlLineaLayout.setVerticalGroup(
            pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        pnlSide.add(pnlLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 80, 5));

        pnlGrado.setBackground(new java.awt.Color(26, 2, 58));
        pnlGrado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlGrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlGradoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlGradoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlGradoMouseExited(evt);
            }
        });

        lblGrado.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        lblGrado.setForeground(new java.awt.Color(255, 255, 255));
        lblGrado.setText("Grado");
        lblGrado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGrado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlGradoLayout = new javax.swing.GroupLayout(pnlGrado);
        pnlGrado.setLayout(pnlGradoLayout);
        pnlGradoLayout.setHorizontalGroup(
            pnlGradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGradoLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(lblGrado)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        pnlGradoLayout.setVerticalGroup(
            pnlGradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGrado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        pnlSide.add(pnlGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 260, 35));

        pnlCurso.setBackground(new java.awt.Color(26, 2, 58));
        pnlCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCursoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlCursoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlCursoMouseExited(evt);
            }
        });

        lblCurso.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        lblCurso.setForeground(new java.awt.Color(255, 255, 255));
        lblCurso.setText("Curso");
        lblCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCurso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlCursoLayout = new javax.swing.GroupLayout(pnlCurso);
        pnlCurso.setLayout(pnlCursoLayout);
        pnlCursoLayout.setHorizontalGroup(
            pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCursoLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(lblCurso)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        pnlCursoLayout.setVerticalGroup(
            pnlCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        pnlSide.add(pnlCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 260, 35));

        pnlDocente.setBackground(new java.awt.Color(26, 2, 58));
        pnlDocente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDocenteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlDocenteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlDocenteMouseExited(evt);
            }
        });

        lblDocente.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        lblDocente.setForeground(new java.awt.Color(255, 255, 255));
        lblDocente.setText("Docente");
        lblDocente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDocente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlDocenteLayout = new javax.swing.GroupLayout(pnlDocente);
        pnlDocente.setLayout(pnlDocenteLayout);
        pnlDocenteLayout.setHorizontalGroup(
            pnlDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDocenteLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(lblDocente)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        pnlDocenteLayout.setVerticalGroup(
            pnlDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDocente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        pnlSide.add(pnlDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 260, 35));

        pnlAlumno.setBackground(new java.awt.Color(26, 2, 58));
        pnlAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAlumnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlAlumnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlAlumnoMouseExited(evt);
            }
        });

        lblAlumno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        lblAlumno.setForeground(new java.awt.Color(255, 255, 255));
        lblAlumno.setText("Alumno");
        lblAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAlumno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlAlumnoLayout = new javax.swing.GroupLayout(pnlAlumno);
        pnlAlumno.setLayout(pnlAlumnoLayout);
        pnlAlumnoLayout.setHorizontalGroup(
            pnlAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlumnoLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(lblAlumno)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        pnlAlumnoLayout.setVerticalGroup(
            pnlAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        pnlSide.add(pnlAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 260, 35));

        pnlApoderado.setBackground(new java.awt.Color(26, 2, 58));
        pnlApoderado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlApoderado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlApoderadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlApoderadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlApoderadoMouseExited(evt);
            }
        });

        lblApoderado.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        lblApoderado.setForeground(new java.awt.Color(255, 255, 255));
        lblApoderado.setText("Apoderados");
        lblApoderado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblApoderado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlApoderadoLayout = new javax.swing.GroupLayout(pnlApoderado);
        pnlApoderado.setLayout(pnlApoderadoLayout);
        pnlApoderadoLayout.setHorizontalGroup(
            pnlApoderadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlApoderadoLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(lblApoderado)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        pnlApoderadoLayout.setVerticalGroup(
            pnlApoderadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblApoderado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        pnlSide.add(pnlApoderado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 260, 35));

        pnlMatriculas.setBackground(new java.awt.Color(26, 2, 58));
        pnlMatriculas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlMatriculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMatriculasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlMatriculasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlMatriculasMouseExited(evt);
            }
        });

        lblMatriculas.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        lblMatriculas.setForeground(new java.awt.Color(255, 255, 255));
        lblMatriculas.setText("Matrículas");
        lblMatriculas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMatriculas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlMatriculasLayout = new javax.swing.GroupLayout(pnlMatriculas);
        pnlMatriculas.setLayout(pnlMatriculasLayout);
        pnlMatriculasLayout.setHorizontalGroup(
            pnlMatriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMatriculasLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(lblMatriculas)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        pnlMatriculasLayout.setVerticalGroup(
            pnlMatriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMatriculas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        pnlSide.add(pnlMatriculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 260, 35));

        pnlCerrarSesion.setBackground(new java.awt.Color(26, 2, 58));
        pnlCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlCerrarSesionMouseExited(evt);
            }
        });

        lblCerrarSesion.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        lblCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrarSesion.setText("Cerrar Sesión");
        lblCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlCerrarSesionLayout = new javax.swing.GroupLayout(pnlCerrarSesion);
        pnlCerrarSesion.setLayout(pnlCerrarSesionLayout);
        pnlCerrarSesionLayout.setHorizontalGroup(
            pnlCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCerrarSesionLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(lblCerrarSesion)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        pnlCerrarSesionLayout.setVerticalGroup(
            pnlCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCerrarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        pnlSide.add(pnlCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 260, 35));

        pnlBack.add(pnlSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 770));

        lblLogoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoPrincipal.png"))); // NOI18N
        lblLogoMenu.setText("jLabel1");
        pnlBack.add(lblLogoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 610, 140, -1));

        pnlPerfil.setBackground(new java.awt.Color(255, 255, 255));
        pnlPerfil.setForeground(new java.awt.Color(26, 2, 58));
        pnlPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPerfilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlPerfilMouseExited(evt);
            }
        });

        lblPerfil.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        lblPerfil.setForeground(new java.awt.Color(26, 2, 58));
        lblPerfil.setText("Perfil");
        lblPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlPerfilLayout = new javax.swing.GroupLayout(pnlPerfil);
        pnlPerfil.setLayout(pnlPerfilLayout);
        pnlPerfilLayout.setHorizontalGroup(
            pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPerfilLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(lblPerfil)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        pnlPerfilLayout.setVerticalGroup(
            pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPerfil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        pnlBack.add(pnlPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 710, 210, -1));

        getContentPane().add(pnlBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1040, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlSecretariaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSecretariaMouseClicked
        DialogSecretaria ds = new DialogSecretaria();
        ds.setVisible(true);
    }//GEN-LAST:event_pnlSecretariaMouseClicked

    private void pnlSecretariaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSecretariaMouseEntered
        pnlSecretaria.setBackground(new Color(168, 181, 240)); //new Color(168, 181, 240) color morado claro
        lblSecretaria.setForeground(new Color(26, 2, 58));
    }//GEN-LAST:event_pnlSecretariaMouseEntered

    private void pnlSecretariaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSecretariaMouseExited
        pnlSecretaria.setBackground(new Color(26, 2, 58)); //new Color(26, 2, 58) azul oscuro
        lblSecretaria.setForeground(Color.WHITE);
    }//GEN-LAST:event_pnlSecretariaMouseExited

    private void pnlGradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGradoMouseClicked
        DialogGrado dg = new DialogGrado();
        dg.setB(false);
        dg.setVisible(true);
    }//GEN-LAST:event_pnlGradoMouseClicked

    private void pnlGradoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGradoMouseEntered
        pnlGrado.setBackground(new Color(168, 181, 240));
        lblGrado.setForeground(new Color(26, 2, 58));
    }//GEN-LAST:event_pnlGradoMouseEntered

    private void pnlGradoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGradoMouseExited
        pnlGrado.setBackground(new Color(26, 2, 58));
        lblGrado.setForeground(Color.WHITE);
    }//GEN-LAST:event_pnlGradoMouseExited

    private void pnlUpperMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUpperMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xCursor, y - yCursor);
    }//GEN-LAST:event_pnlUpperMouseDragged

    private void pnlUpperMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUpperMousePressed
        xCursor = evt.getX();
        yCursor = evt.getY();
    }//GEN-LAST:event_pnlUpperMousePressed

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        pnlExit.setBackground(Color.RED);
        lblExit.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        pnlExit.setBackground(Color.WHITE);
        lblExit.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblExitMouseExited

    private void lblMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_lblMinMouseClicked

    private void lblMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseEntered
        pnlMin.setBackground(new Color(240,240,240));
        lblMin.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblMinMouseEntered

    private void lblMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseExited
        pnlMin.setBackground(Color.WHITE);
        lblMin.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblMinMouseExited

    private void pnlCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCursoMouseClicked
        DialogCurso dc = new DialogCurso();
        dc.setVisible(true);
    }//GEN-LAST:event_pnlCursoMouseClicked

    private void pnlCursoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCursoMouseEntered
        pnlCurso.setBackground(new Color(168, 181, 240));
        lblCurso.setForeground(new Color(26, 2, 58));
    }//GEN-LAST:event_pnlCursoMouseEntered

    private void pnlCursoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCursoMouseExited
        pnlCurso.setBackground(new Color(26, 2, 58));
        lblCurso.setForeground(Color.WHITE);
    }//GEN-LAST:event_pnlCursoMouseExited

    private void pnlDocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDocenteMouseClicked
        DialogDocentes dd = new DialogDocentes();
        dd.setB(false);
        dd.setVisible(true); 
    }//GEN-LAST:event_pnlDocenteMouseClicked

    private void pnlDocenteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDocenteMouseEntered
        pnlDocente.setBackground(new Color(168, 181, 240));
        lblDocente.setForeground(new Color(26, 2, 58));
    }//GEN-LAST:event_pnlDocenteMouseEntered

    private void pnlDocenteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDocenteMouseExited
        pnlDocente.setBackground(new Color(26, 2, 58));
        lblDocente.setForeground(Color.WHITE);
    }//GEN-LAST:event_pnlDocenteMouseExited

    private void pnlAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAlumnoMouseClicked
        DialogAlumno da = new DialogAlumno();
        da.setVisible(true);
    }//GEN-LAST:event_pnlAlumnoMouseClicked

    private void pnlAlumnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAlumnoMouseEntered
        pnlAlumno.setBackground(new Color(168, 181, 240));
        lblAlumno.setForeground(new Color(26, 2, 58));
    }//GEN-LAST:event_pnlAlumnoMouseEntered

    private void pnlAlumnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAlumnoMouseExited
        pnlAlumno.setBackground(new Color(26, 2, 58));
        lblAlumno.setForeground(Color.WHITE);
    }//GEN-LAST:event_pnlAlumnoMouseExited

    private void pnlApoderadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlApoderadoMouseClicked
        // TODO add your handling code here:
        DialogApoderado da = new DialogApoderado();
        da.setVisible(true);
    }//GEN-LAST:event_pnlApoderadoMouseClicked

    private void pnlApoderadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlApoderadoMouseEntered
        // TODO add your handling code here:
        pnlApoderado.setBackground(new Color(168, 181, 240));
        lblApoderado.setForeground(new Color(26, 2, 58));
    }//GEN-LAST:event_pnlApoderadoMouseEntered

    private void pnlApoderadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlApoderadoMouseExited
        // TODO add your handling code here:
        pnlApoderado.setBackground(new Color(26, 2, 58));
        lblApoderado.setForeground(Color.WHITE);
    }//GEN-LAST:event_pnlApoderadoMouseExited

    private void pnlMatriculasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMatriculasMouseClicked
        // TODO add your handling code here:
        DialogRegistroMatricula dm = new DialogRegistroMatricula(secretariaLog);
        dm.setVisible(true);
    }//GEN-LAST:event_pnlMatriculasMouseClicked

    private void pnlMatriculasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMatriculasMouseEntered
        // TODO add your handling code here:
        pnlMatriculas.setBackground(new Color(168, 181, 240));
        lblMatriculas.setForeground(new Color(26, 2, 58));
    }//GEN-LAST:event_pnlMatriculasMouseEntered

    private void pnlMatriculasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMatriculasMouseExited
        // TODO add your handling code here:
        pnlMatriculas.setBackground(new Color(26, 2, 58));
        lblMatriculas.setForeground(Color.WHITE);
    }//GEN-LAST:event_pnlMatriculasMouseExited

    private void pnlCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCerrarSesionMouseClicked
        // TODO add your handling code here:
        secretariaLog = null;
        this.dispose();
        FrmLogin l = new FrmLogin();
        l.setUsuario(null);
        l.setVisible(true);
        
    }//GEN-LAST:event_pnlCerrarSesionMouseClicked

    private void pnlCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCerrarSesionMouseEntered
        // TODO add your handling code here:
        pnlCerrarSesion.setBackground(new Color(168, 181, 240));
        lblCerrarSesion.setForeground(new Color(26, 2, 58));
    }//GEN-LAST:event_pnlCerrarSesionMouseEntered

    private void pnlCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCerrarSesionMouseExited
        // TODO add your handling code here:
        pnlCerrarSesion.setBackground(new Color(26, 2, 58));
        lblCerrarSesion.setForeground(Color.WHITE);
    }//GEN-LAST:event_pnlCerrarSesionMouseExited

    private void pnlPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPerfilMouseClicked
        DialogSecretariaPerfil sp = new DialogSecretariaPerfil();
        sp.setSecretaria(secretariaLog);
        sp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlPerfilMouseClicked

    private void pnlPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPerfilMouseEntered
        pnlPerfil.setBackground(new Color(168, 181, 240)); //new Color(168, 181, 240) color morado claro
        
    }//GEN-LAST:event_pnlPerfilMouseEntered

    private void pnlPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPerfilMouseExited
        pnlPerfil.setBackground(Color.WHITE);
        
    }//GEN-LAST:event_pnlPerfilMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicioSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicioSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicioSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicioSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInicioSecretaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAlumno;
    private javax.swing.JLabel lblApoderado;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDocente;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblGrado;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogoMenu;
    private javax.swing.JLabel lblMatriculas;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblNombreSecretaria;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblSecretaria;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlAlumno;
    private javax.swing.JPanel pnlApoderado;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JPanel pnlCerrarSesion;
    private javax.swing.JPanel pnlCurso;
    private javax.swing.JPanel pnlDocente;
    private javax.swing.JPanel pnlExit;
    private javax.swing.JPanel pnlGrado;
    private javax.swing.JPanel pnlLinea;
    private javax.swing.JPanel pnlMatriculas;
    private javax.swing.JPanel pnlMin;
    private javax.swing.JPanel pnlPerfil;
    private javax.swing.JPanel pnlSecretaria;
    private javax.swing.JPanel pnlSide;
    private javax.swing.JPanel pnlUpper;
    // End of variables declaration//GEN-END:variables
}
