/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import datos.*;
import entidad.*;
import encriptacion.Encriptador;
import java.awt.Color;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author hiro
 */
public class FrmLogin extends javax.swing.JFrame {
    private static FrmLogin instancia;
    Encriptador ENC = Encriptador.getInstancia();
    
    public Usuario usuario = null;
    int xCursor, yCursor;
        
    public static FrmLogin getInstancia(){
        if(instancia==null)
            instancia=new FrmLogin();
        return instancia;
    }
    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        setLocationRelativeTo(null);
        setScaledPhoto(lblCepas, "/img/CepasSinFondo.png");
        // Para ícono del programa
        ImageIcon iconoFrm = new ImageIcon(getClass().getResource("/img/logoPrincipal.png"));
        this.setIconImage(iconoFrm.getImage()); 
    }

    public void setScaledPhoto(JLabel lbl, String route){
        ImageIcon img = new ImageIcon(getClass().getResource("/img/CepasSinFondo.png"));
        Icon icono = new ImageIcon(img.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), 1));
        lbl.setIcon(icono);
    }
    
    public void setUsuario(Usuario u){
        usuario = u;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        lblErrorUsu = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        pnlUpper = new javax.swing.JPanel();
        pnlExit = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        lblIntranet = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblCepas = new javax.swing.JLabel();
        pnlLinea = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        lblPassw = new javax.swing.JLabel();
        lblDNI = new javax.swing.JLabel();
        txtPassw = new javax.swing.JPasswordField();
        lblErrorPass = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        pnlIngresar = new javax.swing.JPanel();
        lblIngresar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblErrorUsu.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        lblErrorUsu.setForeground(new java.awt.Color(255, 0, 51));
        pnlMain.add(lblErrorUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 450, 20));

        lblLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoPrincipal.png"))); // NOI18N
        pnlMain.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 610, -1, -1));

        pnlUpper.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlUpperMouseDragged(evt);
            }
        });
        pnlUpper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlUpperMousePressed(evt);
            }
        });
        pnlUpper.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlExit.setBackground(new java.awt.Color(255, 255, 255));
        pnlExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblExit.setBackground(new java.awt.Color(255, 255, 255));
        lblExit.setFont(new java.awt.Font("Yu Gothic", 0, 16)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("X");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        pnlExit.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 0, 80, 30));

        pnlUpper.add(pnlExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 80, 40));

        lblIntranet.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lblIntranet.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIntranet.setText("Intranet");
        pnlUpper.add(lblIntranet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 60, 30));

        pnlMain.add(pnlUpper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 30));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FondoFiltroAzul.png"))); // NOI18N
        lblImage.setText("jLabel2");
        pnlMain.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, -10, 390, 770));

        lblCepas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CepasSinFondo.png"))); // NOI18N
        lblCepas.setText("jLabel1");
        pnlMain.add(lblCepas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 220, 210));

        pnlLinea.setBackground(new java.awt.Color(26, 2, 58));

        javax.swing.GroupLayout pnlLineaLayout = new javax.swing.GroupLayout(pnlLinea);
        pnlLinea.setLayout(pnlLineaLayout);
        pnlLineaLayout.setHorizontalGroup(
            pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        pnlLineaLayout.setVerticalGroup(
            pnlLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlMain.add(pnlLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 220, 5));

        lblTitulo.setFont(new java.awt.Font("Yu Gothic", 0, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(26, 2, 58));
        lblTitulo.setText("Inicio de sesión");
        pnlMain.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 280, 40));

        txtDNI.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        txtDNI.setBorder(null);
        txtDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDNIMouseClicked(evt);
            }
        });
        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });
        txtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDNIKeyTyped(evt);
            }
        });
        pnlMain.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 380, 40));

        lblPassw.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        lblPassw.setForeground(new java.awt.Color(26, 4, 59));
        lblPassw.setText("Contraseña");
        pnlMain.add(lblPassw, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 280, 40));

        lblDNI.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        lblDNI.setForeground(new java.awt.Color(26, 2, 58));
        lblDNI.setText("DNI");
        pnlMain.add(lblDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 280, 40));

        txtPassw.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        txtPassw.setBorder(null);
        txtPassw.setVerifyInputWhenFocusTarget(false);
        txtPassw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswMouseClicked(evt);
            }
        });
        pnlMain.add(txtPassw, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 340, 40));

        lblErrorPass.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        lblErrorPass.setForeground(new java.awt.Color(255, 0, 51));
        pnlMain.add(lblErrorPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 410, 20));
        pnlMain.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 410, 30));
        pnlMain.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 410, 30));

        pnlIngresar.setBackground(new java.awt.Color(26, 2, 58));
        pnlIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlIngresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlIngresarMouseExited(evt);
            }
        });

        lblIngresar.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lblIngresar.setForeground(new java.awt.Color(255, 255, 255));
        lblIngresar.setText("Ingresar");
        lblIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlIngresarLayout = new javax.swing.GroupLayout(pnlIngresar);
        pnlIngresar.setLayout(pnlIngresarLayout);
        pnlIngresarLayout.setHorizontalGroup(
            pnlIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresarLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lblIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        pnlIngresarLayout.setVerticalGroup(
            pnlIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIngresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlMain.add(pnlIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 260, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 747, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIActionPerformed

    private void pnlUpperMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUpperMousePressed
        xCursor = evt.getX();
        yCursor = evt.getY();
    }//GEN-LAST:event_pnlUpperMousePressed

    private void pnlUpperMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUpperMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xCursor, y - yCursor);
    }//GEN-LAST:event_pnlUpperMouseDragged

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        pnlExit.setBackground(Color.RED);
        lblExit.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        pnlExit.setBackground(new Color(240, 240, 240));
        lblExit.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblExitMouseExited

    private void pnlIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlIngresarMouseEntered
        pnlIngresar.setBackground(new Color(168, 181, 240));
        lblIngresar.setForeground(new Color(26, 2, 58));
    }//GEN-LAST:event_pnlIngresarMouseEntered

    private void pnlIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlIngresarMouseExited
        pnlIngresar.setBackground(new Color(26, 2, 58));
        lblIngresar.setForeground(Color.WHITE);
    }//GEN-LAST:event_pnlIngresarMouseExited

    private void txtDNIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDNIMouseClicked
      
    }//GEN-LAST:event_txtDNIMouseClicked

    private void txtPasswMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswMouseClicked
       
    }//GEN-LAST:event_txtPasswMouseClicked

    private void pnlIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlIngresarMouseClicked
        try { 
           String dni = txtDNI.getText(); 
           String pword = new String(txtPassw.getPassword());
           pword = ENC.SHA256(pword);
           usuario = UsuarioDAO.getInstancia().buscarUsuario(dni); 
           lblErrorUsu.setText(""); 
           lblErrorPass.setText(""); 
           Matricula m = null; 
           if(usuario==null) 
           {         
                  lblErrorUsu.setText("El número de DNI ingresado no está conectado a una cuenta"); 
                  txtDNI.requestFocus(); 
           }else{ 
               
               boolean esValido = UsuarioDAO.getInstancia().validarUsuario(dni, pword); 
               if(esValido){ 
                
               m = MatriculaDAO.getInstancia().buscarMatriculaPorDniAlumno(dni); 
                
               if(m==null || !m.getAlumno().getDni().equals(dni)) 
               { 
                   usuario = DocenteDAO.getInstancia().buscarDocente(dni); 
                   if(usuario==null) 
                   { 
                       usuario = SecretariaDAO.getInstancia().buscarSecretaria(dni); 
                       if(usuario!=null){ 
                        FrmInicioSecretaria s = new FrmInicioSecretaria(); 
                        s.setSecretariaLog((Secretaria) usuario); 
                        s.setVisible(true); 
                        this.dispose(); 
                       }else lblErrorUsu.setText("El número de DNI ingresado no está conectado a una cuenta"); 
                        
                   } 
                   else{ 
                       FrmInicioDocente d = new FrmInicioDocente(); 
                       d.setDocenteLog((Docente) usuario); 
                       d.setVisible(true); 
                       this.dispose();        
                   } 
               } 
               else{                 
                   if(AlumnoDAO.getInstancia().buscarAlumno(dni)!=null){ 
                       usuario = AlumnoDAO.getInstancia().buscarAlumno(dni); 
                       FrmInicioAlumno a = new FrmInicioAlumno(); 
                       a.setAlumnoLog((Alumno) usuario); 
                       a.setVisible(true); 
                       this.dispose(); 
                   } 
               } 
                
               } 
               else{ 
                   lblErrorPass.setText("Contraseña incorrecta"); 
                   txtPassw.requestFocus(); 
 
               } 
           } 
        } catch(SQLException ex){ 
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage()); 
        } catch (NoSuchAlgorithmException ex) {
            System.out.println("Error: "+ex.getMessage());
        }
       
    }//GEN-LAST:event_pnlIngresarMouseClicked

    private void txtDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        String id = txtDNI.getText();
        
        if(!Character.isDigit(c)){
             evt.consume();
         }
        if(id.length()==8)
            evt.consume();
    }//GEN-LAST:event_txtDNIKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCepas;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblErrorPass;
    private javax.swing.JLabel lblErrorUsu;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblIngresar;
    private javax.swing.JLabel lblIntranet;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPassw;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlExit;
    private javax.swing.JPanel pnlIngresar;
    private javax.swing.JPanel pnlLinea;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlUpper;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JPasswordField txtPassw;
    // End of variables declaration//GEN-END:variables
}
